### ISSUE TITLE
accessing the rows in vaex dataframe.

### ISSUE THREAD

**Issue by RAJAT8878** [vaexio/vaex#494] opened 2019-12-10 11:25 UTC
In pandas, we have a facility for accessing the rows from loc or iloc method. Is there any way by which we can access the specific rows for vaex dataframe.

**Comment by maartenbreddels** [comment] 2019-12-13 16:05
Vaex has no index (yet), so by default all access is row based.
This should work.
```python
import vaex
df = vaex.example()
df['x'].values[0]
```
Note that if x is virtual column, every time you access `.values` it will have to be computed (thus slow). So you may want to assign it to a local variable. If x is too large, you may want to get a chunk:
```python
import vaex
df = vaex.example()
chunk = df['x'][:10000].values
chunk[0]
```

What is the reason to access an individual value, may I ask?

**Comment by RAJAT8878** [comment] 2020-02-16 15:14
Hi @maartenbreddels  It's not about accessing an individual value or not any columns value. Let's suppose i wanted  to filter by index  where index is in timestamp format. since loc and iloc is very common for selecting the subset of data based on the condition.

**Comment by maartenbreddels** [comment] 2020-02-17 14:12
Could you be more specific on what you want, like give a pandas example? Thanks!

**Comment by JovanVeljanoski** [comment] 2020-04-12 21:35
Will close this as stale -  please reopen if needed. Thanks!

**Closed by JovanVeljanoski** 2020-04-12 21:35 UTC

**Comment by calebjacksonhoward** [comment] 2020-07-23 17:21
How might I do this sort of selective modification of a vaex dataframe?

```
import pandas as pd
import numpy as np

id      = [2, 3, 7, 9, 10, 11]
truth   = [False, False, False, False, False, False]
df      = pd.DataFrame({'id': id, 'truth': truth})

filter      = [3, 10]
selection   = [i in filter for i in id]

df.loc[selection, 'truth'] = True

print(df)

```

**Comment by vijaybabupalli** [comment] 2020-09-01 22:49
In pandas, we have a facility for accessing the rows from loc or iloc method. Is there any way by which we can access the specific rows for vaex dataframe.

**Comment by FrancescoSaverioZuppichini** [comment] 2022-07-10 17:36
any update?

**Comment by NickCrews** [comment] 2022-08-25 03:35
FYI the issue is closed, so maintainers aren't going to look at it. Open a new issue if you need it, and please be specific with what you need. The solution that was posted works great for accessing specific rows and columns.

@calebjacksonhoward, for selective modifcation, you need to use `where()`: https://vaex.io/docs/api.html#vaex.expression.Expression.where

**Comment by chaoshunihao** [comment] 2023-05-13 15:39
import vaex
df=vaex.example()
df[1:5]
