### ISSUE TITLE
can't use functions like vaex.join or vaex.rename

### ISSUE THREAD

**Issue by anarchy89** [vaexio/vaex#667] opened 2020-04-12 05:58 UTC
I installed vaex using the conda forge channel first, and then I switched to pip. I tried the functions vaex.join and vaex.rename. When I try to use them, it says that module vaex 

> AttributeError: module 'vaex' has no attribute 'join'
or
> AttributeError: module 'vaex' has no attribute 'rename'

I get the same error when I try
> print(vaex.join.__file__)

I can get other functions to work like vaex.from_pandas or vaex.from_csv

I'm using a fresh miniconda environment on mac os.

**Comment by JovanVeljanoski** [comment] 2020-04-12 07:41
Hi, 

What do you mean by "and than I switched to pip". Did you try to reinstall vaex from pip on top of the conda installation, or after some point, you started installing additional packages from pip instead of conda-forge?

If case one, something in the installation has gotten wrong, best to install fresh from the beginning. If case two: well that should not happen. 

When you import vaex, can you try and see where the installation is coming from?

**Comment by anarchy89** [comment] 2020-04-12 07:44
I created a new conda environment, install vaex from conda forge, got that error, uninstalled vaex from conda, deleted the environment, created a new environment, used pip install vaex, got the same error

**Comment by anarchy89** [comment] 2020-04-12 07:45
How can I see where it’s coming from?

**Comment by JovanVeljanoski** [comment] 2020-04-12 07:47
Google is your friend :)

```
import vaex

print(vaex.__file__)
```

**Comment by anarchy89** [comment] 2020-04-12 07:50
>import vaex
>print(vaex.__file__)

gives the following output. 

>~/miniconda3/envs/vaex/lib/python3.7/site-packages/__init__.py

**Comment by JovanVeljanoski** [comment] 2020-04-12 08:09
hm.. I am not 100% but from this it looks like the installation has not gone well. 

You can try reinstalling, but before you need to check that no vaex packages (or the meta) package is in `conda list`. 

If you import some other external library like numpy or pandas you will the above link as something like:
`~/miniconda3/envs/vaex/lib/python3.7/site-packages/pandas/__init__.py `.

**Comment by anarchy89** [comment] 2020-04-12 08:39
I tried installing it in a fresh environment on my windows10 pc, using this `conda install -c conda-forge vaex-core vaex-viz vaex-jupyter vaex-arrow vaex-server vaex-ui vaex-hdf5 vaex-astro vaex-distributed` and i got the exact same error. This time the output of vaex file is `D:\Users\XXX\Anaconda3\envs\ml\lib\site-packages\vaex\__init__.py`

**Comment by maartenbreddels** [comment] 2020-04-12 09:37
There does not exist a vaex.join, only df.join, do you call it? If not
could you provide a full stack trace?

(from mobile phone)

**Comment by anarchy89** [comment] 2020-04-12 09:47
I first do `df = vaex.from_csv(data.csv, index_col=0)` then, `print(df)`.

I get this`
#      VALUE    index
0      65.35     1900-01-01
1      51.73     1900-02-01
2      58.39     1900-03-01
3      51.42     1900-04-01
4      51.39     1900-05-01
...    ...      ...
1,195  32.88     2018-08-01
1,196  31.98     2018-09-01
1,197  41.14     2018-10-01
1,198  42.22     2018-11-01
1,199  42.02     2018-12-01
`
Then I run `df = df.rename("VALUE","Data1")`

I get the following error 
`
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-7c794011a56a> in <module>

---> 11     df = df.rename("VALUE","Data1")


~/miniconda3/envs/spark/lib/python3.7/site-packages/vaex/dataframe.py in __getattr__(self, name)
    227             return self.__hidden__[name].__get__(self)
    228         else:
--> 229             return object.__getattribute__(self, name)
    230 
    231     @property

AttributeError: 'DataFrameArrays' object has no attribute 'rename'
`

**Comment by JovanVeljanoski** [comment] 2020-04-12 15:05
I can not reproduce your rename issue i am afraid. 

Note that renaming is done in place, so should be 
```
df.rename('name', 'new_name')
```

In any case, i do think there is something wrong with your installation.

Note for future: it is better and preferred to open separate issues  for each problem you encounter. It is better/easier to track problems, discussions and solutions. 

For the rename problem, depending on your usecase, you can simply do something like 
```
df['new_name'] = df['old_name']
```
No memory/resources are spent anyway. 

Also from your stacktrace i see that the two separate issues you are reporting here come from two separate environments.

**Comment by JovanVeljanoski** [comment] 2020-04-12 15:11
I will close this issue as it becomes messy and hard to trace.

Please open separate issue for each problem you encounter, if needed. Please look at the docs first as well as [vaex-examples](https://github.com/vaexio/vaex-examples) and [vaex-talks](https://github.com/vaexio/vaex-talks) repos for additional notebook examples, especially for join.

My general recommendation would be to start with a _clean_ install. Note that sometimes when using miniconda3, information seems to leak from one environment to another. I've not been able to consistently reproduce it, but I've felt the effect (and frustration) from it.

**Closed by JovanVeljanoski** 2020-04-12 15:11 UTC
