### ISSUE TITLE
hello, i want to ask about the groupby function

### ISSUE THREAD

**Issue by steven1536796418** [vaexio/vaex#779] opened 2020-06-01 14:12 UTC
my code as such:
`
#data_ is the pd.DataFrame 
data = vaex.from_pandas(data_)
data.groupby("creative_id").agg("age":"mean")
`
however, it occus that "'DatasetArrays' object has no attribute 'groupby'" , how to address this problem?
Thanks.

**Comment by JovanVeljanoski** [comment] 2020-06-01 14:51
Hi, 

First of all your syntax is a bit wrong, should be 
`data.groupby("creative_id").agg({"age": "mean"})`

But I can't reproduce the issue. Probably there is something wrong with your installation. Can you share which version of vaex you have, and how you installed it?

**Comment by steven1536796418** [comment] 2020-06-01 14:57
Thank for your reply.
Yes, the syntax is wrong, i just want to point the worng, the version is '1.0.0-beta.6', and i installed it in the anaconda through the command "conda&nbsp;install&nbsp;-c&nbsp;conda-forge&nbsp;vaex".
I create the pandas.DataFrame firstly, and the DataFrame's shape is about (6,300,000, 2).




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jovan Veljanoski"<notifications@github.com&gt;; 
发送时间: 2020年6月1日(星期一) 晚上10:52
收件人: "vaexio/vaex"<vaex@noreply.github.com&gt;; 
抄送: "天地景逸"<1536796418@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [vaexio/vaex] hello, i want to ask about the groupby function (#779)



Hi,
 First of all your syntax is a bit wrong, should be
 data.groupby("creative_id").agg({"age": "mean"})
 But I can't reproduce the issue. Probably there is something wrong with your installation. Can you share which version of vaex you have, and how you installed it?

**Comment by JovanVeljanoski** [comment] 2020-06-01 15:14
Hm.. for some reason it looks like you have (very?) old version of vaex. 

If you are using conda, try
`conda search -c conda-forge vaex`
and choose a more recent version. Perhaps something like
`conda install -c conda-forge vaex==2.6.0`  or whatever is most recent. 
you can also try
`conda install -c conda-forge vaex-core==2.0.1`

**Comment by steven1536796418** [comment] 2020-06-01 15:20
ok， thanks， I have a try.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jovan Veljanoski"<notifications@github.com&gt;; 
发送时间: 2020年6月1日(星期一) 晚上11:15
收件人: "vaexio/vaex"<vaex@noreply.github.com&gt;; 
抄送: "天地景逸"<1536796418@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [vaexio/vaex] hello, i want to ask about the groupby function (#779)



Hm.. for some reason it looks like you have (very?) old version of vaex.
 If you are using conda, try
 conda search -c conda-forge vaex
 and choose a more recent version. Perhaps something like
 conda install -c conda-forge vaex==2.6.0or whatever is most recent.
 you can also try
 conda install -c conda-forge vaex-core==2.0.1

**Comment by maartenbreddels** [comment] 2020-06-02 07:24
There was an issue with the latest release (we basically did not have vaex 3.0 on conda-forge), but this is now fixed:
https://anaconda.org/conda-forge/vaex

If the problem persists, please reopen and let us know.

**Closed by maartenbreddels** 2020-06-02 07:24 UTC
