### ISSUE TITLE
[BUG-REPORT] groupby error: ArrowInvalid: offset overflow while concatenating arrays

### ISSUE THREAD

**Issue by KrzysztofPrzygodzki** [vaexio/vaex#1750] opened 2021-11-28 12:44 UTC
Hi there!

Thanks for developing and sharing Vaex!

I have encountered a bug in `groupby`, that I originally refereed to in other thread. I was explicitly asked by @maartenbreddels ([here](https://github.com/vaexio/vaex/issues/746#issuecomment-980075133)) to write about it in a new issue.

I'm using Vaex installed by `pip` with Python 3.8.12 on CentOS Linux release 7.9.2009 (Core).
'vaex': '4.5.0'
'vaex-core': '4.5.1'
'vaex-viz': '0.5.0'
'vaex-hdf5': '0.10.0'
'vaex-server': '0.6.1'
'vaex-astro': '0.9.0'
'vaex-jupyter': '0.6.0'
'vaex-ml': '0.14.0'

I think error is connected with abusing function `take` in  `pyarrow`. It was already described somewhere among other issues. 

**ERROR stack-trace**
```python
---------------------------------------------------------------------------
ArrowInvalid                              Traceback (most recent call last)
/mnt/nfs/kprzygodzki/projects/cpc/src/error_reproduction.py in <module>
----> 18 groups = df.groupby(by=["x", "y"], agg=vaex.agg.count())

/mnt/nfs/kprzygodzki/miniconda3/envs/cpc/lib/python3.8/site-packages/vaex/dataframe.py in groupby(self, by, agg, sort, assume_sparse, row_limit)
   6677         """
   6678         from .groupby import GroupBy
-> 6679         groupby = GroupBy(self, by=by, sort=sort, combine=assume_sparse, row_limit=row_limit)
   6680         if agg is None:
   6681             return groupby

/mnt/nfs/kprzygodzki/miniconda3/envs/cpc/lib/python3.8/site-packages/vaex/groupby.py in __init__(self, df, by, sort, combine, expand, row_limit)
    480     """Implementation of the binning and aggregation of data, see :method:`groupby`."""
    481     def __init__(self, df, by, sort=False, combine=False, expand=True, row_limit=None):
--> 482         super(GroupBy, self).__init__(df, by, sort=sort, combine=combine, expand=expand, row_limit=row_limit)
    483 
    484     def agg(self, actions):

/mnt/nfs/kprzygodzki/miniconda3/envs/cpc/lib/python3.8/site-packages/vaex/groupby.py in __init__(self, df, by, sort, combine, expand, row_limit)
    323             if occupancy < 10:
    324                 logger.info(f'Combining {len(self.by)} groupers into 1')
--> 325                 self.by = [_combine(self.df, self.by, sort=sort, row_limit=row_limit)]
    326                 self.combine = True
    327             else:

/mnt/nfs/kprzygodzki/miniconda3/envs/cpc/lib/python3.8/site-packages/vaex/groupby.py in _combine(df, groupers, sort, row_limit)
    282         binby_expressions[i] = binby_expression
    283     expression = reduce(operator.add, binby_expressions)
--> 284     grouper = GrouperCombined(expression, df, multipliers=cumulative_counts[1:], parents=combine_now, sort=sort, row_limit=row_limit)
    285     if combine_later:
    286         # recursively add more of the groupers (because of 64 bit overflow)

/mnt/nfs/kprzygodzki/miniconda3/envs/cpc/lib/python3.8/site-packages/vaex/groupby.py in __init__(self, expression, df, multipliers, parents, sort, row_limit)
    209                     # bin_values[field.name] = pa.DictionaryArray.from_arrays(indices, ar)
    210             else:
--> 211                 bin_values[parent.label] = parent.bin_values.take(indices)
    212                 # bin_values[parent.label] = pa.DictionaryArray.from_arrays(indices, parent.bin_values)
    213         self.bin_values = pa.StructArray.from_arrays(bin_values.values(), bin_values.keys())

/mnt/nfs/kprzygodzki/miniconda3/envs/cpc/lib/python3.8/site-packages/pyarrow/table.pxi in pyarrow.lib.ChunkedArray.take()

/mnt/nfs/kprzygodzki/miniconda3/envs/cpc/lib/python3.8/site-packages/pyarrow/compute.py in take(data, indices, boundscheck, memory_pool)
    588     """
    589     options = TakeOptions(boundscheck=boundscheck)
--> 590     return call_function('take', [data, indices], options, memory_pool)
    591 
    592 

/mnt/nfs/kprzygodzki/miniconda3/envs/cpc/lib/python3.8/site-packages/pyarrow/_compute.pyx in pyarrow._compute.call_function()

/mnt/nfs/kprzygodzki/miniconda3/envs/cpc/lib/python3.8/site-packages/pyarrow/_compute.pyx in pyarrow._compute.Function.call()

/mnt/nfs/kprzygodzki/miniconda3/envs/cpc/lib/python3.8/site-packages/pyarrow/error.pxi in pyarrow.lib.pyarrow_internal_check_status()

/mnt/nfs/kprzygodzki/miniconda3/envs/cpc/lib/python3.8/site-packages/pyarrow/error.pxi in pyarrow.lib.check_status()

ArrowInvalid: offset overflow while concatenating arrays
```
 
I created small snippet that reproduces this error. However, you need around 150-200 GB RAM to directly use it.
It may look very artificial, but for me it was actually problematic. My data set has 130M+ rows and a high cardinality of columns used for grouping. Columns consisted IDs in form of a strings. 

```python
import vaex
import numpy as np
import string

# Create quite a long string
test_length = int(1e6)
long_Text = "".join(np.random.choice(np.array(list(string.ascii_letters)), test_length))

# Create small dataset with this long string
number_of_rows = 10000

# create many groups by concatanting long string with random number 
x = np.array([long_Text + str(np.random.rand()) for _ in range(number_of_rows)])
y = np.array([long_Text + str(np.random.rand()) for _ in range(number_of_rows)])

df = vaex.from_arrays(x=x, y=y)

groups = df.groupby(by=["x", "y"], agg=vaex.agg.count())

```

**Comment by maartenbreddels** [comment] 2021-12-16 09:25
You example costed me too much memory to run, I tried:
```
def test_groupby_large_string():
    long_string = "a" * int(1e6)

    # Create small dataset with this long string
    number_of_rows = 10000

    x = pa.array([long_string] * 10_000)
    y = pa.array([long_string] * 10_000)

    df = vaex.from_arrays(x=x, y=y)
    groups = df.groupby(by=["x", "y"], agg=vaex.agg.count())
```

But this runs fine for me. What version or pyarrow are you using, and can you test maybe with the latest release (4.6)

**Comment by fangxingjun** [comment] 2022-01-08 02:50
i have the same problem like it, my data size is about 4500million. and my data is made up by 4 hdf5 files.

**Comment by fangxingjun** [comment] 2022-01-08 02:54
the version of vaex is 4.7.

**Comment by fangxingjun** [comment] 2022-01-08 03:08
i have to find the way to solve the problem, so i select the cols which we need to be grouped, but i use the api of to_pandas_df. just like this:

**Comment by fangxingjun** [comment] 2022-01-08 09:19
yeah， i just runed it and it worked,  maybe the problem is that i have concat 4 hdf5 files, and then i used df.sort, finally when i drop_duplicates and failed. i had try many ways to solve it, but when i used 1 file but not 4 files, and then i success.

**Comment by JovanVeljanoski** [comment] 2022-03-12 21:56
I will close this - please re-open if needed. 

Note: the output of sort is a shallow copy of the original dataframe, but in order to sort, the column (or columns) that is used to sorting is temporarily put in memory. This is necessary to be able to perform the sorting operation.

**Closed by JovanVeljanoski** 2022-03-12 21:56 UTC
