### ISSUE TITLE
 fillna func with blank values convert column from sting type to object type 

### ISSUE THREAD

**Issue by salwaen** [vaexio/vaex#948] opened 2020-08-28 08:59 UTC
Hi, 

### i have column with type string has none 

````
#       groupno    Name
0       0          name1
1       0          name1
2       0          name1
3       0          name1
4       1          name1
...     ...        ...
36,766  1          None
36,767  2          None
36,768  3          None
36,769  4          None
36,770  4          None
[----------------------------------------]  0.00% estimated time: unknown

````

````
print(vaex_df.Name.dtype)
````
### Output
````
<class 'str'>
````

###  with fillna func 
````
 vaex_df = vaex_df.fillna(value='', column_names=['Name'])
 print(vaex_df[['groupno', 'Name']])
 print(vaex_df['Name'].dtype))
````
### Output
````
#       groupno    Name
0       0            nam1
1       0            nam1
2       0            nam1
3       0            nam1
4       1            nam1
...     ...        ...
36,766  1
36,767  2
36,768  3
36,769  4
36,770  4
object
````
### export to HDF5 
````
df_vaex.export_hdf5('./data/io/output_data.hdf5')
````

### Output
````
TypeError: Object dtype dtype('O') has no native HDF5 equivalent
2020-08-28 10:38:59,196 root [ERROR] error creating dataset for 'Name', with type dtype('O') 
````
I know HDF5 doesn't supports object type, is there a solution?
thanks

**Comment by JovanVeljanoski** [comment] 2020-08-31 16:02
Yeah I think this is a bug..

How do you read in the data into vaex to begin with?

If you use something like `pandas.read_csv` or `vaex.read_csv` (which is the same), vaex will automatically try to convert dtype objects into to best possible primitive dtype. If it can't it will try to convert it to string. Sometimes (I've not been able to consistently reproduce this - might try later this week), this process does not go as planned, and the underlying data structure is still on some level considered of dtype object.

So in the meantime, there is a workaround. The best way is to read in the data as a pandas dataframe, and clean it there such that the data contains only primitive types (ints, floats, strings). Then you can pass it to vaex `vaex.from_pandas(..)` and all should be fine. 

I will mark this as bug, and hopefully we can reproduce it!

**Comment by salwaen** [comment] 2020-08-31 18:04
I read the data  with   `pd.read_sql_query` then into vaex  ` vaex .from_pandas()`

> So in the meantime, there is a workaround. The best way is to read in the data as a pandas dataframe, and clean it there such that the data contains only primitive types (ints, floats, strings). Then you can pass it to vaex vaex.from_pandas(..) and all should be fine.

Yes I did that as you said. thanks

**Comment by JovanVeljanoski** [comment] 2020-08-31 20:44
Hey, I can't reproduce the problem with my ideas.

Can you please tell me what kind of data triggered it so we can fix it? 

It could already be fixed in master.. i am not 100% sure

**Comment by maartenbreddels** [comment] 2020-09-21 10:14
Fixed in https://github.com/vaexio/vaex/pull/865

**Closed by maartenbreddels** 2020-09-21 10:14 UTC
Labels: bug
