### ISSUE TITLE
`isin` Not Working Properly

### ISSUE THREAD

**Issue by Alon-Alexander** [vaexio/vaex#631] opened 2020-03-05 10:43 UTC
Hi,
Putting an example usage here.
Do you have any idea why isn't it working as it is supposed to (like pandas `isin`)?

![image](https://user-images.githubusercontent.com/19497150/75974016-c7705580-5ede-11ea-8d43-9b68c0b3935d.png)

**Comment by JovanVeljanoski** [comment] 2020-03-05 11:15
Hi @Alon-Alexander 

Thanks for the report and for the reproducible example!

Curious.. if you instantiate a vaex dataframe via numpy, there is no such problem.. My guess is that this has something to do with the 'object' type of pandas, but I am not sure. It should have been converted to string..  (screenshot below).

@maartenbreddels should I make a test for this and classify as bug?

![image](https://user-images.githubusercontent.com/18574951/75976544-ed93f680-5eda-11ea-91c8-6b1e30e20928.png)

**Comment by maartenbreddels** [comment] 2020-04-09 08:06
yeah, please do, looks like a bug.

**Comment by maartenbreddels** [comment] 2020-04-15 07:03
Fixed in #669

**Closed by maartenbreddels** 2020-04-15 07:03 UTC
Labels: bug, priority: high
