### ISSUE TITLE
percentile_approx returns nan

### ISSUE THREAD

**Issue by alrz199** [vaexio/vaex#844] opened 2020-06-18 06:48 UTC
hi
 i have latest version of vaex and percentile_approx always returns nan for me. 
for example:
i have this df:
a	b
a1	2
a2	1
a3	3
a4	5
a5	6
df_t.percentile_approx('b', percentage=75.0) returns nan 
i checked numpy percentile and it works well
np.percentile([2,1,3,5,6],90) returns 5.6

**Comment by JovanVeljanoski** [comment] 2020-06-18 07:19
Hi @alrz199 

I can't reproduce it..
<img width="613" alt="image" src="https://user-images.githubusercontent.com/18574951/84989928-b6251f00-b144-11ea-808b-edf7b77eaaf1.png">


Can you share your OS, numpy version and `vaex.__version__`

**Comment by alrz199** [comment] 2020-06-18 07:27
os: windows 10
np.__version__:1.18.1
vaex.__version__:
'vaex': '3.0.0',
'vaex-core': '2.0.1',
'vaex-viz': '0.4.0',
'vaex-hdf5': '0.6.0',
'vaex-server': '0.3.0',
'vaex-astro': '0.7.0',
'vaex-jupyter': '0.5.0',
'vaex-ml': '0.9.0',
'vaex-arrow': '0.5.0'

**Comment by maartenbreddels** [comment] 2020-06-18 07:37
Ah, it's this issue that we only see on CI, but are never able to reproduce locally! Duplicate of #385 .

**Comment by alrz199** [comment] 2020-06-18 08:09
thank you @maartenbreddels 
downgrade numpy to 1.16 solved problem. sorry i didnt check #385

**Closed** 2020-06-18 08:09 UTC

**Comment by maartenbreddels** [comment] 2020-06-18 08:12
No problem, that happens, thanks for reporting!
