### ISSUE TITLE
Removing Astropy as a dependency 

### ISSUE THREAD

**Issue by datascienceit** [vaexio/vaex#47] opened 2017-10-18 20:35 UTC
To make it more lightweight.

**Comment by mfouesneau** [comment] 2017-11-02 09:05
But you would loose the VO connection with UCDs and Units.

**Comment by datascienceit** [comment] 2017-11-02 09:20
That is a great feature, but I have never encountered a business problem who had it, I think it's very science\research oriented, and therefore rather only import it when needed.

**Comment by maartenbreddels** [comment] 2017-11-02 09:46
Just to give some background, veax will be split into several packages (currently in the packages branch, 'soon' to be merged), to name a few:
 * vaex-core (all core algos)
 * vaex-astro (astronomy related stuff)

For vaex-core, only the astropy.units module is really required, but could be optional (units and ucd would be optional, and if astropy is not installed, would simply be treated as strings, so they will not get lost on exporting the data). The vaex-astro package would depend on astropy also for other modules, and that bring in full fledged support for units.
The issue is that it is a bit difficult to test, I'd probably have to run a few unittests without astropy installed to implement this reliable.
So, units should not disappear, but I agree the dependency on astropy is kind of a heavy weight.

**Closed** 2021-06-04 13:46 UTC
