### ISSUE TITLE
Nested execute call in Keras generator

### ISSUE THREAD

**Issue by fabero** [vaexio/vaex#750] opened 2020-05-19 12:51 UTC
Good afternoon,

While working on a custom data generator using vaex for a Keras model, I ran into a RuntimeError: nested execute call after some time.

This is the code for the generator:

```
	class DataGenerator(keras.utils.Sequence):
	def __init__(self, list_IDs, filename, labels, batch_size=128, shuffle=True, top_k=10000, dim=(2, 1422)):
		self.filename = filename
		self.batch_size = batch_size
		self.shuffle = shuffle
		self.list_IDs = list_IDs
		self.dim = dim
		self.labels = labels
		self.tokenizer = Tokenizer(num_words=top_k, oov_token='<unk>')
		self.df = vaex.open(filename+'.hdf5')
		self.on_epoch_end()

	def __len__(self):
		'Denotes the number of batches per epoch'
		return int(np.floor(len(self.list_IDs) / self.batch_size))

	def __getitem__(self, index):
		'Generate one batch of data'
		# Generate indexes of the batchaaa
		indexes = self.indexes[index*self.batch_size:(index+1)*self.batch_size]

		# Find list of IDs
		list_IDs_temp = set([self.list_IDs[k] for k in indexes])

		# Generate data
		X, y = self.__data_generation(list_IDs_temp)

		return X, y
 
	def on_epoch_end(self):
		'Updates indexes after each epoch'
		self.indexes = np.arange(len(self.list_IDs))
		if self.shuffle == True:
			np.random.shuffle(self.indexes)

	def __data_generation(self, list_IDs_temp):
		'Generates data containing batch_size samples'
		# start = time.time()
		# Initialization
		X = np.empty((self.batch_size, *self.dim))
		y = np.empty((self.batch_size), dtype=int)
		for i, ID in enumerate(list_IDs_temp):
			# start = time.time()
			row = self.df[self.df.id == ID]
			# print('retrieval took {} sec'.format(start - time.time()))
			text1 = row['text1'].values[0]
			text2 = row['text2'].values[0]
			self.tokenizer.fit_on_texts([text1, text2])
			tokenizedA = self.tokenizer.texts_to_sequences([text1])
			tokenizedB = self.tokenizer.texts_to_sequences([text2])
			X[i,0,:] = pad_sequences(tokenizedA, padding='post', maxlen=self.dim[1])[0]
			X[i,1,:] = pad_sequences(tokenizedB, padding='post', maxlen=self.dim[1])[0]
			y[i] = self.labels[ID]
		# print('took {}'.format(time.time() - start))
		return [X[:,0], X[:,1]], y		
```

I use two instances of DataGenerator: 

```
tr_gen = DataGenerator(ids[train_index], args.dataset, labels, args.batch_size, True, 10000, (2, args.max_len))
va_gen = DataGenerator(ids[test_index], args.dataset, labels, args.batch_size, True, 10000, (2, args.max_len))
```

The crash occurs when Keras starts to evaluate, and starts using the second generator. I have a feeling the issue might be caused by the double access but am not sure.

The error that was returned:

```
150/151 [============================>.] - ETA: 1s - loss: 0.1323 - accuracy: 0.7730 - auroc: 0.7737Traceback (most recent call last):
  File "siamese.py", line 201, in <module>
    main(args)
  File "siamese.py", line 168, in main
    validation_data=va_gen, callbacks=[time_callback])
  File "/home/s/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1433, in fit_generator
    steps_name='steps_per_epoch')
  File "/home/s/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 322, in model_iteration
    steps_name='validation_steps')
  File "/home/s/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 220, in model_iteration
    batch_data = _get_next_batch(generator, mode)
  File "/home/s/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 362, in _get_next_batch
    generator_output = next(generator)
  File "/home/s/.local/lib/python3.6/site-packages/tensorflow/python/keras/utils/data_utils.py", line 785, in get
    six.reraise(*sys.exc_info())
  File "/home/s/.local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/s/.local/lib/python3.6/site-packages/tensorflow/python/keras/utils/data_utils.py", line 779, in get
    inputs = self.queue.get(block=True).get()
  File "/software/software/Python/3.6.6-foss-2018b/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/software/software/Python/3.6.6-foss-2018b/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/s/.local/lib/python3.6/site-packages/tensorflow/python/keras/utils/data_utils.py", line 571, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "/data/s/thesis/vaex_generator.py", line 34, in __getitem__
    X, y = self.__data_generation(list_IDs_temp)
  File "/data/s2/thesis/vaex_generator.py", line 54, in __data_generation
    text1 = row['text1'].values[0]
  File "/home/s/.local/lib/python3.6/site-packages/vaex/expression.py", line 320, in values
    return self.evaluate()
  File "/home/s/.local/lib/python3.6/site-packages/vaex/expression.py", line 668, in evaluate
    return self.ds.evaluate(self, i1, i2, out=out, selection=selection, parallel=parallel)
  File "/home/s/.local/lib/python3.6/site-packages/vaex/dataframe.py", line 5120, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "/home/s/.local/lib/python3.6/site-packages/vaex/dataframe.py", line 5177, in _evaluate_implementation
    max_stop = (len(self) if (self.filtered and filtered) else self.length_unfiltered())
  File "/home/s/.local/lib/python3.6/site-packages/vaex/dataframe.py", line 3715, in __len__
    self. _cached_filtered_length = int(self.count())
  File "/home/s/.local/lib/python3.6/site-packages/vaex/dataframe.py", line 711, in count
    return self._compute_agg('count', expression, binby, limits, shape, selection, delay, edges, progress)
  File "/home/s/.local/lib/python3.6/site-packages/vaex/dataframe.py", line 686, in _compute_agg
    return self._delay(delay, var)
  File "/home/s/.local/lib/python3.6/site-packages/vaex/dataframe.py", line 1428, in _delay
    self.execute()
  File "/home/s/.local/lib/python3.6/site-packages/vaex/dataframe.py", line 293, in execute
    self.executor.execute()
  File "/home/s/.local/lib/python3.6/site-packages/vaex/execution.py", line 127, in execute
    raise RuntimeError("nested execute call")
RuntimeError: nested execute call
```

Does any of you see what the issue is here? A solution maybe, or am I using Vaex in a wrong way here? 

Thanks in advance.

**Comment by JovanVeljanoski** [comment] 2020-05-19 13:02
Hi @fabero 

This sounds like something that was recently fixed but not officially released yet. 
We have an alpha version out that you can try which includes the fix:
```
pip install vaex-core==2.0.0a5
pip install vaex-hdf5==0.6.0a1
```

Otherwise you can try a install from source if you are comfortable with that.

Actually, we are also thinking of providing a better tensorflow/keras interface for data manipulated through vaex, you can see #622. But I remember running into similar issues as you, which should be fixed now in the alpha release (and of course in master).

I hope this helps, and please let us know how it turns out.

**Comment by fabero** [comment] 2020-05-19 19:59
> pip install vaex-hdf5==0.6.0a1

Hi @JovanVeljanoski ,

Thank you for your reply.

Doing these installs seems to break vaex on my machine. I get the following error:

```
Traceback (most recent call last):
  File "siamese_glove.py", line 17, in <module>
    from vaex_generator import DataGenerator
  File "/data/s/thesis/vaex_generator.py", line 6, in <module>
    import vaex
  File "/home/s/.local/lib/python3.6/site-packages/vaex/__init__.py", line 40, in <module>
    import vaex.dataframe
  File "/home/s/.local/lib/python3.6/site-packages/vaex/dataframe.py", line 17, in <module>
    import vaex.utils
  File "/home/s/.local/lib/python3.6/site-packages/vaex/utils.py", line 24, in <module>
    from .column import str_type
  File "/home/s/.local/lib/python3.6/site-packages/vaex/column.py", line 10, in <module>
    import vaex.strings
  File "/home/s/.local/lib/python3.6/site-packages/vaex/strings.py", line 7, in <module>
    from .superstrings import *
ImportError: /home/s/.local/lib/python3.6/site-packages/vaex/superstrings.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN7pcrecpp2RE4InitERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKNS_10RE_OptionsE
```

Do you have any idea what the cause of this is?


I also tried completely removing vaex and reinstalling it from source. This results in the same error.

**Comment by maartenbreddels** [comment] 2020-05-19 20:12
Which is/version is this? I'll try to reproduce this in docker.

(from mobile phone)

**Comment by maartenbreddels** [comment] 2020-05-19 20:36
Auto correct at work.
Which OS (not 'is') and version are you using?

**Comment by maartenbreddels** [comment] 2020-05-19 20:39
> I also tried completely removing vaex and reinstalling it from source. This results in the same error.

make sure you uninstall vaex-core, veax is only a meta package that installs all vaex subpackages.

**Comment by fabero** [comment] 2020-05-20 08:27
> Auto correct at work.
> Which OS (not 'is') and version are you using?

I am using CentOS Linux release 7.7.1908.

**Comment by maartenbreddels** [comment] 2020-05-22 14:50
I played in a docker container, and noticed that with the system python3, it tries to compile psutil and vaex-core from source. I think you pip is out of date:
```
pip install -U pip
```
should help, after that the commands by Jovan should run really fast (it will not have to compile).


I am not sure why compiling from source didn't work for you though, but if this works it shouldn't matter right?

**Comment by fabero** [comment] 2020-05-25 12:37
I updated pip to version 20.1 and ran the two pip installs, and it worked!

Many thanks to you both @maartenbreddels @JovanVeljanoski !

**Closed** 2020-05-25 12:37 UTC

**Comment by maartenbreddels** [comment] 2020-05-25 12:46
Good to hear that, thanks for letting us know. I hope to do a final release today, worst case this week.
