### ISSUE TITLE
vaex.example() fails

### ISSUE THREAD

**Issue by akotlar** [vaexio/vaex#727] opened 2020-05-08 01:10 UTC
Url missing http://vaex.astro.rug.nl/data/ does not exist, and neither does https://...

**Comment by JovanVeljanoski** [comment] 2020-05-08 07:08
Hi @akotlar 

This is a duplicate of #169. Please refer to that issue. The links are updated in master, and will be available in the next release.

**Closed by JovanVeljanoski** 2020-05-08 07:08 UTC

**Comment by akotlar** [comment] 2020-05-08 13:55
Ah sorry about that, had done a quick search missed the existing issue. Thanks!
