### ISSUE TITLE
[BUG-REPORT] sort by 2 columns with different ordering yields unexpected behavior

### ISSUE THREAD

**Issue by Ben-Epstein** [vaexio/vaex#1631] opened 2021-10-12 16:35 UTC
Thank you for reaching out and helping us improve Vaex!

Before you submit a new Issue, please read through the [documentation](https://docs.vaex.io/en/latest/). Also, make sure you search through the Open and Closed Issues - your problem may already be discussed or addressed.

**Description**
Vaex dataframes can currently be sorted by 2 columns, but when specifying a value for `ascending` if you pass in a list of booleans (like in Pandas), it will `bool` the entire expression and return all columns ordered by that single bool.

The expected behavior should either be to follow the users specification, or throw an error saying that this functionality isn't currently supported.

Example:
```
import vaex
from random import random
import numpy as np
n = 100
col1 = np.random.randint(0, 20, size=n)
col2 = np.random.randint(0, 20, size=n)
arrays = {
    'col1': col1,
    'col2': col2
}
M = vaex.from_arrays(**arrays)
M.sort(by=['col1','col2'], ascending=[True, False])
```

For some more context, see this result:
![image](https://user-images.githubusercontent.com/22605641/136994979-ba2c55cf-5d85-41a7-91c0-460c5dd67f5d.png)
When 2 rows have the same value for `col1` you should expect col2 to be sorted descending, but it's not. 

By comparison, the same code done with pandas 
```
M.to_pandas_df().sort_values(by=['col1','col2'], ascending=[True, False])
```
yields
![image](https://user-images.githubusercontent.com/22605641/136995215-bf06f818-9daa-4055-bce0-674a10e5295d.png)

Not supporting this yet seems reasonable to me, but in that case the function should fail given the value passed to `ascending`

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`:
```
{'vaex': '4.5.0',
 'vaex-core': '4.5.1',
 'vaex-viz': '0.5.0',
 'vaex-hdf5': '0.10.0',
 'vaex-server': '0.6.1',
 'vaex-astro': '0.9.0',
 'vaex-jupyter': '0.6.0',
 'vaex-ml': '0.14.0'}
```
 - Vaex was installed via: pip / conda-forge / from source : pip
 - OS: macOS big sur

**Additional information**
Please state any supplementary information or provide additional context for the problem (e.g. screenshots, data, etc..).

**Comment by JovanVeljanoski** [comment] 2021-11-13 22:50
The behavior that you describe is simply not supported. I think the docstrings make that clear:

> :param bool ascending: ascending (default, True) or descending (False)

**Comment by JovanVeljanoski** [comment] 2021-11-13 23:16
Closing as duplicate of https://github.com/vaexio/vaex/issues/815

**Closed by JovanVeljanoski** 2021-11-13 23:16 UTC

**Comment by Ben-Epstein** [comment] 2021-11-14 15:46
@JovanVeljanoski I think it's reasonable to not support it, but I think you should actively throw an exception when a user tries to. Otherwise, you have very unexpected results on the client side. I'll open a PR with what I mean

**Comment by Ben-Epstein** [comment] 2021-11-14 15:46
@JovanVeljanoski  https://github.com/vaexio/vaex/pull/1703
