### ISSUE TITLE
[BUG-REPORT]

### ISSUE THREAD

**Issue by jasonkmoore** [vaexio/vaex#1241] opened 2021-03-06 16:31 UTC
# Background
Before submitting this as a new Issue, I read through the documentation at https://docs.vaex.io/en/latest/ and searched through the Open and Closed Issues. It appears my issue may be related to open issues: #644, #585, and closed issue #417. It seems like it should have been resolved with #186. and I tried using the technique @maartenbreddels  described in the conversation (https://github.com/vaexio/vaex/pull/186#issue-257686153), but could not resolve the issue.

# Software information
 - Vaex version: {'vaex': '3.0.0',  'vaex-core': '2.0.3',  'vaex-viz': '0.4.0',  'vaex-hdf5': '0.6.0',  'vaex-server': '0.3.1',  'vaex-astro': '0.7.0',  'vaex-ui': '0.3.0',  'vaex-jupyter': '0.5.2',  'vaex-ml': '0.9.0',  'vaex-arrow': '0.5.1'}
 - Vaex was installed via: pip 
 - OS: Linux/Pop!_OS Pop!; version 20.10"

# Description
## Need:
I am converting millions of polygon strings into arrays of floats so that I can leverage Vaex's inside_polygon function, which I expect is much faster and easier on memory than its equivalent in geopandas or shapely.

## Problem: 
Converting polygon string -> array of strings -> array of floats generate a "ValueError: could not broadcast input array from shape ... into shape ..." It works flawlessly if each polygon string is of equal length (i.e., has the same number of points for each record). It throws the ValueError if the resulting arrays are of different length. Pandas does not generate the error in either scenario.  

### Data:  two rows of equal length polygons (9 pairs of lat long)

test['a'] = [
    '-82.9394 35.3602 -82.9396 35.3605 -82.9396 35.3606 \
     -82.9396 35.3607 -82.9393 35.3609 -82.9391 35.3611 \
     -82.9390 35.3612 -82.9388 35.3612 -82.9387 35.3612',     
    '-82.9430 35.3517 -82.9428 35.3516 -82.9425 35.3513 \
     -82.9422 35.3511 -82.9422 35.3510 -82.9424 35.3510 \
     -82.9425 35.3509 -82.9426 35.3509 -82.9426 35.3508' 
    ]

### Data: two rows of unequal length polygons (9 pairs in first row, 12 pairs in second row)

test['b'] = [
    '-82.9394 35.3602 -82.9396 35.3605 -82.9396 35.3606 \
     -82.9396 35.3607 -82.9393 35.3609 -82.9391 35.3611 \
     -82.9390 35.3612 -82.9388 35.3612 -82.9387 35.3612', 
    '-82.9430 35.3517 -82.9428 35.3516 -82.9425 35.3513 \
     -82.9422 35.3511 -82.9422 35.3510 -82.9424 35.3510 \
     -82.9425 35.3509 -82.9426 35.3509 -82.9426 35.3508 \
     -82.9426 35.3503 -82.9427 35.3500 -82.9428 35.3498' 
    ]

### Code: string to array of float values. Both work if running in Pandas, only column a works if using vaex.

test['a_longitude'] = test.a.apply(lambda x: np.array(x.split()).astype('float64')[::2])
test['b_longitude'] = test.b.apply(lambda x: np.array(x.split()).astype('float64')[::2])

### Code: Convert the Pandas DataFrame to Vaex and running again will throw an error for column b.

test = vaex.from_pandas(test[['a','b']])
test['a_longitude'] = test.a.apply(lambda x: np.array(x.split()).astype('float64')[::2])
test['b_longitude'] = test.b.apply(lambda x: np.array(x.split()).astype('float64')[::2])

# Additional information
Attaching a zipped file with the notebook that demonstrates each step in both Pandas and Vaex.
[FasterPolygonsWithVaex.zip](https://github.com/vaexio/vaex/files/6095677/FasterPolygonsWithVaex.zip)

**Comment by JovanVeljanoski** [comment] 2021-03-06 18:18
Hi, 

I think there are two things to consider here. So the closed/merged issues you referred to - for that you need to install the latest alpha
`pip install vaex==4.0.0a13`.

If you have to continue working with the stable v3, then the process below would be the same, but at the end you need to join on the final list elements, as v3 did not support storage of lists (or any support is accidental and untested). 

Now for the actual issue you are facing, i propose the following:
In your lambda you do `x.split()` which returns a python list, and as far as I know you can't really do `astype()` on it, since that is more of a numpy thing. 

Thus, I have re-written your lambda as: 
```
def func(x):
    x = np.array(x.split()).astype(float)
    x = x[::2].tolist()
    return x
```

This seems to work:
<img width="637" alt="image" src="https://user-images.githubusercontent.com/18574951/110216474-b66e7180-7eaf-11eb-8e1a-ded3c30313fb.png">


The drawback is that, the output lists are still "strings" technically., but if you do something like `df.new_a.tolist()` or `df.new_a.to_numpy()` you would get the desired format. I guess that should be fine, since at the moment there arent really any list operations in vaex (on the roadmap however!) apart from doing more `apply` on them. 

I hope this helps a bit - please let us know how it goes! 

P.S.: I have to comment - it is a true pleasure getting a nicely explained problem, with a reproducible example! Thank you for that! :)

**Comment by jasonkmoore** [comment] 2021-03-06 21:03
Hi Jovan. Thanks for the super fast reply.  I did not all expect a response so soon; I've been looking for work arounds and missed that you already replied.  I will give it a try on my project and let you you know how it goes.

**Comment by jasonkmoore** [comment] 2021-03-23 23:21
For unrelated reasons, I switched my approach to using APIs and running the point in polygon directly from the host server.  That said, I was able to get this to work.  Thank you for the help.

My attempt at applying the function you provided returned an error of "AttributeError: 'list' object has no attribute 'split'" when running against vaex expression. My mistake, in trying to provide a simplified example, I overlooked detailing that part.  When I mentioned I was converting polygons into floats, I should have also explained that the text I was converting to numpy was actually a virtual column based on a regex expression of a different column in the data.  Nevertheless - the code below worked and though it did use up a bit of memory, it did not kill the kernel, which is impressive given that it represented more than 7.6million rows and I'm on a laptop with 7.5Gb RAM. Below is a fuller representation of the code.  As noted - it worked and the 

dataframe
# | ATTRIBUTE | WETLAND_TYPE | geometry
-- | -- | -- | --
0 | 'E1AB3L' | 'Estuarine and Marine Deepwater' | "'MULTIPOLYGON (((-88.3034 30.3804, -88.3034 30....
1 | 'E1AB3L' | 'Estuarine and Marine Deepwater' | "'MULTIPOLYGON (((-88.2699 30.3875, -88.2701 30.


` 
# create virtual column that strips the text and parenthesis from the 'geometry' text 
v_usda['temp'] = v_usda.geometry.str.replace(pat = '(multi-polygon|polygon |,|\(|\))', 
                                     repl='', 
                                     n=-1, 
                                     regex = True, 
                                     flags = re.IGNORECASE).str.split()

# define a function that iterates through each item, converting strings to floats 
def hmf(s):
    for i in range(len(s)): 
        s[i] = s[i].astype(float)
    return(s)

# create virtual long/lat columns from string representing list of number pairs
v_usda['long'] = hmf(v_usda.temp.apply(lambda x: np.array(x)[::2]).to_numpy())
v_usda['lat'] = hmf(v_usda.temp.apply(lambda x: np.array(x)[1::2]).to_numpy())

# get rid of the temp column after processing.
del v_nwi['temp']`

**Closed** 2021-03-23 23:21 UTC
