### ISSUE TITLE
Virtual Column coordinates __xxx_matrix not found / Stride != 8

### ISSUE THREAD

**Issue by mfouesneau** [vaexio/vaex#40] opened 2017-09-18 07:47 UTC
A strange bug appears when I add a virtual column like 
```
cat.add_virtual_columns_eq2gal('RAout', 'DECout')
```
I can evaluate the column but when I try to select upon it I get a strange message:
```
error name '__celestial_eq2gal_matrix' is not defined
```

**Comment by maartenbreddels** [comment] 2017-09-18 08:30
I'm trying to reproduce this but cannot (for master and 1.0.0b6), can you give a small self contained example that shows this?
(Hint: `ds = vaex.from_scalars(ra=1, dec=2)` may be useful)

**Comment by mfouesneau** [comment] 2017-09-18 11:46
Here is one example:

```
N = int(1e4)
ra = np.random.uniform(0, 360, N)
dec = np.random.uniform(0, 180, N)
ds = vaex.from_arrays(ra=ra, dec=dec)
ds.add_virtual_columns_eq2gal()
ds.plot1d('ra', selection='l < 0')


NameError: name '__celestial_eq2gal_matrix' is not defined
```

**Comment by maartenbreddels** [comment] 2017-09-18 14:37
I don't get this error, quite strange. Which version do you run, I guess you installed the latest release(1.0.0b6) after the previous issue right? From pip?

**Comment by mfouesneau** [comment] 2017-09-18 15:47
I ran pip again and now I have a broken python library

```libc++abi.dylib:terminating with uncaught exception of type Error: stride is not equal to 1```

It seems matplotlib can run so I don't know what happened. That will take a while to figure.

**Comment by maartenbreddels** [comment] 2017-09-18 16:37
It seems that msg comes from vaex actually, try git master otherwise, it will give an error but should not crash.

**Comment by mfouesneau** [comment] 2017-09-18 16:38
I don't know, it really crashes the python kernel so I have no way to find where it is from

**Comment by mfouesneau** [comment] 2017-09-18 16:44
interestingly... if I open a file with vaex it seems to work (did not test long) but if I create a dataset from arrays it crashes with the above error.  Seems it is from vaex.

**Comment by maartenbreddels** [comment] 2017-09-18 16:56
The arrays you feed into vaex need to have a stride of 1, to if you do sth like 2d_blob[:,2], it will not take it since it is not optimal.

**Comment by mfouesneau** [comment] 2017-09-18 16:58
data arrays are 1d arrays. vaex can export them into a file and read it back without the error.
It must be something that is not cast when in memory

**Comment by maartenbreddels** [comment] 2017-09-18 16:58
If you `.copy()` it, I should work btw.

**Comment by mfouesneau** [comment] 2017-09-18 17:00
.copy() on what?

**Comment by mfouesneau** [comment] 2017-09-18 17:18
ok found something interesting I think.
(I already installed the git/master version)

The following code triggers the error:
```
uniform = np.random.uniform
Npop = int(1e6)
pop = np.random.uniform(0, 10, (Npop, 3))
samples = {
    'ra': pop[:, 0],
    'dec': np.rad2deg(np.arcsin(pop[:, 1])),
    'gmag' : pop[:, 2]}
ds = vaex.from_arrays(**samples)
ds.plot1d('ra')
```

However, if I ravel the individual variables as follow is does not generate an error
```
samples = {
    'ra': pop[:, 0].ravel(),
    'dec': np.rad2deg(np.arcsin(pop[:, 1])).ravel(),
    'gmag' : pop[:, 2].ravel()}
ds = vaex.from_arrays(**samples)
ds.plot1d('ra')
```

**Comment by maartenbreddels** [comment] 2017-09-18 17:23
Indeed, `.copy()` gives you the same effect. Let me show you the strides for a 3x3 array:
![screen shot 2017-09-18 at 19 20 25](https://user-images.githubusercontent.com/1765949/30554964-7655f58a-9ca6-11e7-9455-ca2f1a58828b.png)
When the stride is 8 (and the itemsize is 8, in vaex I divide by the itemsize, so that's why I complain it is not 1), it means the next item is directly at the next memory location. When the strides is 24, as shown above, it means the next item is 3 location apart, which is bad for performance. But I should check this when constructing the dataset I think, instead of later on when doing the binning.

**Comment by mfouesneau** [comment] 2017-09-18 17:28
I am surprised it is not caught by numpy conversion to C.
The data extracted from 2d arrays are not aligned in any specific way, esp. not 'C'.

I found the `asfloat()` in the legacy.py but that's not enough apparently.

**Comment by maartenbreddels** [comment] 2017-09-18 17:31
Well, it shouldn't accept it, but I think vaex should warn at this part:
```python
ds = vaex.from_arrays(**...)
```
I could try to support strides != itemsize, I just want to avoid getting poor performance.

**Comment by mfouesneau** [comment] 2017-09-18 17:37
I think you could force the contiguous data:

in `dataset.py` line 3588:   
```self.columns[name] = f_or_array```
replaced by 
```self.columns[name] = np.array(f_or_array, copy=False, order='C')```

It seems to do the trick. I don't know where else you need it though.

**Comment by maartenbreddels** [comment] 2017-09-18 17:49
Maybe the best method would be to not convert it, when emit a warning. And indeed allow it, even though it may give bad performance.

**Comment by mfouesneau** [comment] 2017-09-18 17:51
I agree but that is still better than the current runtimeError
The best could be a test

```python
if isinstance(f_or_array, np.array):
     if not f_or_array.flags['C_CONTIGUOUS']:
           warn....
           self.columns[name] = np.array(f_or_array, copy=False, order='C')
```

**Comment by mfouesneau** [comment] 2017-09-18 17:55
FYI, the initial bug: ```error name '__celestial_eq2gal_matrix' is not defined```

seems gone with the git/master version

**Comment by maartenbreddels** [comment] 2017-09-18 17:56
👍  great, I'll keep this open to support stride != (1 or 8)

**Comment by mfouesneau** [comment] 2017-09-18 17:58
Parsing quickly the code, I think you need to wrap `vaexfast` functions with a contiguous parsing.
It seems you call those functions only on chunks. maybe that's what you meant with the binning?

(Thanks for being so present!)

**Comment by maartenbreddels** [comment] 2017-09-18 18:00
What do you mean with 'contiguous parsing'?
Yes, those functions are only used on the 'chunks', so just before calling these functions I could check for the stride and convert on the fly (for small datasets that is ok).
Thanks for testing out!

**Comment by mfouesneau** [comment] 2017-09-18 18:33
I don't know how easy it is to update your C code directly. 

you're welcome. Awesome work that makes my life easier!

**Comment by maartenbreddels** [comment] 2017-09-18 18:35
I am thinking of converting vaex' c codebase to c++ using the xtensor library, it will shrink the codebase quite a lot, and will make it easier to support different strides.
The c code needs a lot of cleaning anyway, quite some dead code in there anyway. But for the moment the conversion can be done on the Python side.

**Comment by mfouesneau** [comment] 2017-09-18 18:48
That'd be great. Xtensor is really an interesting library.

**Comment by maartenbreddels** [comment] 2017-09-18 19:01
Yes indeed, @SylvainCorlay was pushing me to try it out, and the first tests show it gives me the same performance.

**Comment by mfouesneau** [comment] 2017-09-18 19:49
My only issue with xtensor is the C++14 need that is still not standard on old systems. This needs at least GCC 4.9 or 5 I believe.

**Comment by maartenbreddels** [comment] 2017-09-18 20:08
True.. vaex 2.0 then ;)

**Comment by maartenbreddels** [comment] 2019-04-23 15:14
This is fixed in master, and also supported in the refactor of #197 where this is also tested.

**Closed by maartenbreddels** 2019-04-23 15:14 UTC
