### ISSUE TITLE
Use row number in an expression?

### ISSUE THREAD

**Issue by claforte** [vaexio/vaex#250] opened 2019-05-09 13:40 UTC
Hi, is there a memory-efficient way to have an expression use the row number? (ideally with and without selection)?

Here's why I'm asking. I have a data set that consists in "optimization steps" containing 2 columns x 81000 rows. Each step is guaranteed to have the same number of rows. I currently have 3K of these optimizations steps (total 2GBs on disk), and hope to handle 10-50X more in long-term. I need to apply calculation within and across all optimizations steps. I currently concatenate all rows, i.e. end up with 256M rows.

If I can access the row number from an expression, I could calculate:
`vx_df['step'] = vx_df.row / 81000 # i.e. number of rows in one step`
`vx_df['call'] = vx_df.row % 81000  # i.e. this is the original row number within that step`

Is that possible today? Or would it require a new feature, maybe related to #238 ?

I get the feeling that I could somehow pass a `range` object but I'm not sure how to avoid it being flattened and consume tons of memory. e.g. if I do:
`vx_df['row_num'] = list(range(len(df)))`
... peak working memory goes up the roof (from 4GBs to 23GB), my Windows 10 PC becomes unresponsives for 5 minutes, etc. I could make it work by adding it gradually before concatenation but that would mean a lot of wasted memory...

Thank you very much!

**Comment by maartenbreddels** [comment] 2019-05-09 19:04
Absolutely, if you take a look at https://towardsdatascience.com/vaex-a-dataframe-with-super-strings-789b92e8d861 you'll see `vaex.vrange` is being used to create a googol length dataframe. 
```
vf['rownr`] = vaex.vrange(0, len(vf))
```
Let me know if that works out for you.

**Comment by claforte** [comment] 2019-05-09 21:30
Thanks Maarten! Thanks for pointing the interesting article! It would be helpful if `vrange` was properly documented in docs. I can try to update the Tutorial notebook. I'll see if I can spare some time this week or the next. :-)

BTW I tried the code:
```
import vaex
import numpy as np
N = 10**100 # 1 googol
df = vaex.from_arrays(x=vaex.vrange(1, N+1))
df['digits'] = df.x.format('%.0f')
df
```

It produced 2 errors in this line: `df['digits'] = df.x.format('%.0f').str.len()`:

```
ERROR:MainThread:vaex:error evaluating: digits at rows 9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999995-10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\miniopt\lib\site-packages\vaex\scopes.py", line 86, in evaluate
    result = self[expression]
  File "D:\ProgramData\Anaconda3\envs\miniopt\lib\site-packages\vaex\scopes.py", line 133, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: 'Unknown variables or column: "format(x, \'%.0f\')"'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\miniopt\lib\site-packages\vaex\dataframe.py", line 3376, in table_part
    values[name] = self.evaluate(name, i1=k1, i2=k2)
  File "D:\ProgramData\Anaconda3\envs\miniopt\lib\site-packages\vaex\dataframe.py", line 4713, in evaluate
    value = scope.evaluate(expression)
  File "D:\ProgramData\Anaconda3\envs\miniopt\lib\site-packages\vaex\scopes.py", line 86, in evaluate
    result = self[expression]
  File "D:\ProgramData\Anaconda3\envs\miniopt\lib\site-packages\vaex\scopes.py", line 128, in __getitem__
    self.values[variable] = self.evaluate(expression)  # , out=self.buffers[variable])
  File "D:\ProgramData\Anaconda3\envs\miniopt\lib\site-packages\vaex\scopes.py", line 92, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "D:\ProgramData\Anaconda3\envs\miniopt\lib\site-packages\vaex\functions.py", line 1713, in format
    sl = vaex.strings.format(x, format)
RuntimeError: Invalid format
``` 
(...repeated 2X)

But the vrange itself seems to work fine. Thanks again!

**Comment by claforte** [comment] 2019-05-09 21:39
Sorry, I closed by accident. BTW, displaying `df` works, but trying to display `df.x` causes this error:

```
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
D:\ProgramData\Anaconda3\envs\miniopt\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

D:\ProgramData\Anaconda3\envs\miniopt\lib\site-packages\IPython\lib\pretty.py in pretty(self, obj)
    400                         if cls is not object \
    401                                 and callable(cls.__dict__.get('__repr__')):
--> 402                             return _repr_pprint(obj, self, cycle)
    403 
    404             return _default_pprint(obj, self, cycle)

D:\ProgramData\Anaconda3\envs\miniopt\lib\site-packages\IPython\lib\pretty.py in _repr_pprint(obj, p, cycle)
    695     """A pprint that just redirects to the normal repr function."""
    696     # Find newlines and replace them with p.break_()
--> 697     output = repr(obj)
    698     for idx,output_line in enumerate(output.splitlines()):
    699         if idx:

D:\ProgramData\Anaconda3\envs\miniopt\lib\site-packages\vaex\expression.py in __repr__(self)
    243 
    244     def __repr__(self):
--> 245         return self._repr_plain_()
    246 
    247     def _repr_plain_(self):

D:\ProgramData\Anaconda3\envs\miniopt\lib\site-packages\vaex\expression.py in _repr_plain_(self)
    282         else:
    283             state = "expression"
--> 284         line = 'Length: {:,} dtype: {} ({})\n'.format(len(self.ds), dtype, state)
    285         info += line
    286         info += '-' * (len(line)-1) + '\n'

OverflowError: cannot fit 'int' into an index-sized integer
```

The error for `df.x` disappears if I pick a sufficiently small N, e.g. 10**18.

For me, 10**18 rows is more than enough, but I thought you might want to know since you advertise the googol example. ;-)

BTW I'm on Windows 10 64-bits, using Python 3.7.

**Comment by maartenbreddels** [comment] 2019-08-30 06:54
Hah, yeah, the googol example was just for fun, the problem is that Python really cannot work well with it, I'll keep it as a wontfix.

**Closed by maartenbreddels** 2019-08-30 06:54 UTC
