### ISSUE TITLE
[BUG-REPORT] Installation fails on Monterey V12.1 (Apple M1)

### ISSUE THREAD

**Issue by Raidus** [vaexio/vaex#1994] opened 2022-03-29 11:27 UTC
**Description**
Hi,

the installation fails on my Mac M1 Max (Monterey V12.1)

**Software information**
````
conda create --name ds-eyva-search-api-v4 python=3.9
export MACOSX_DEPLOYMENT_TARGET="11" && pip install vaex
````
**Additional information**
```
 ERROR: Command errored out with exit status 1:
     command: /Users/usr/miniconda3/envs/ds-eyva-search-api-v4/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/k2/7321ff_s2rv1cphl835x1trh0000gn/T/pip-install-2zf82ewm/llvmlite_973f21dbac804c64848268faf37accb5/setup.py'"'"'; __file__='"'"'/private/var/folders/k2/7321ff_s2rv1cphl835x1trh0000gn/T/pip-install-2zf82ewm/llvmlite_973f21dbac804c64848268faf37accb5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/k2/7321ff_s2rv1cphl835x1trh0000gn/T/pip-record-5dzpfm8y/install-record.txt --single-version-externally-managed --compile --install-headers /Users/usr/miniconda3/envs/ds-eyva-search-api-v4/include/python3.9/llvmlite
         cwd: /private/var/folders/k2/7321ff_s2rv1cphl835x1trh0000gn/T/pip-install-2zf82ewm/llvmlite_973f21dbac804c64848268faf37accb5/
    Complete output (14 lines):
    running install
    running build
    got version from file /private/var/folders/k2/7321ff_s2rv1cphl835x1trh0000gn/T/pip-install-2zf82ewm/llvmlite_973f21dbac804c64848268faf37accb5/llvmlite/_version.py {'version': '0.38.0', 'full': 'f0365b91ce1e1f74c68785c6d0067f32f89857d9'}
    running build_ext
    /Users/usr/miniconda3/envs/ds-eyva-search-api-v4/bin/python /private/var/folders/k2/7321ff_s2rv1cphl835x1trh0000gn/T/pip-install-2zf82ewm/llvmlite_973f21dbac804c64848268faf37accb5/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/private/var/folders/k2/7321ff_s2rv1cphl835x1trh0000gn/T/pip-install-2zf82ewm/llvmlite_973f21dbac804c64848268faf37accb5/ffi/build.py", line 220, in <module>
        main()
      File "/private/var/folders/k2/7321ff_s2rv1cphl835x1trh0000gn/T/pip-install-2zf82ewm/llvmlite_973f21dbac804c64848268faf37accb5/ffi/build.py", line 214, in main
        main_posix('osx', '.dylib')
      File "/private/var/folders/k2/7321ff_s2rv1cphl835x1trh0000gn/T/pip-install-2zf82ewm/llvmlite_973f21dbac804c64848268faf37accb5/ffi/build.py", line 134, in main_posix
        raise RuntimeError(msg) from None
    RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help.
    error: command '/Users/usr/miniconda3/envs/ds-eyva-search-api-v4/bin/python' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/usr/miniconda3/envs/ds-eyva-search-api-v4/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/k2/7321ff_s2rv1cphl835x1trh0000gn/T/pip-install-2zf82ewm/llvmlite_973f21dbac804c64848268faf37accb5/setup.py'"'"'; __file__='"'"'/private/var/folders/k2/7321ff_s2rv1cphl835x1trh0000gn/T/pip-install-2zf82ewm/llvmlite_973f21dbac804c64848268faf37accb5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/k2/7321ff_s2rv1cphl835x1trh0000gn/T/pip-record-5dzpfm8y/install-record.txt --single-version-externally-managed --compile --install-headers /Users/usr/miniconda3/envs/ds-eyva-search-api-v4/include/python3.9/llvmlite Check the logs for full command output.
```

Any M1 user here who can help out? :-)

Best
Wilhelm

**Comment by JovanVeljanoski** [comment] 2022-03-29 11:42
Closing a duplicate of https://github.com/vaexio/vaex/issues/1903

For M1, at least for now please use miniconda/mamba and install vaex from conda-forge.

**Closed by JovanVeljanoski** 2022-03-29 11:42 UTC
