### ISSUE TITLE
[FEATURE-REQUEST] how to make custom function in groupby

### ISSUE THREAD

**Issue by sungreong** [vaexio/vaex#1312] opened 2021-04-09 05:44 UTC
I want to use a custom function in groupby in vaex, how do I do it?
I confirmed that the apply function does not work.
```
def custom_func(x):
    return x["value"].astype(str).values.tolist()
result = test_base.groupby(["dd"]).apply(cusom_func)
```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-59-615e58785860> in <module>
      1 def custom_func(x):
      2     return x["value"].astype(str).values.tolist()
----> 3 result = test_base.groupby(["order_id"]).apply(cusom_func)

AttributeError: 'GroupBy' object has no attribute 'apply'

**Comment by JovanVeljanoski** [comment] 2021-04-09 17:53
Hi, 

Custom aggregators are currently not supported. We would really want to have such a thing in vaex - but unfortunatey it will require a lot of work to make sure everything runs fast and reliably on proper big data. 

So we are looking for someone to fund this work. If you know of ways to obtain funding for this please get in touch!

Also, I am not 100% sure at this point, but I might be able to give you like a "hacky" possibly sub-optimal way of achieving what you want, not sure how reliable it would be..

ALso I will close this as it is duplicate of #752 . Let's continue any further discussion there, so everything is contained in one place (easier to find)

**Closed by JovanVeljanoski** 2021-04-09 17:53 UTC
