### ISSUE TITLE
[BUG-REPORT]

### ISSUE THREAD

**Issue by karan-doshi** [vaexio/vaex#1723] opened 2021-11-19 12:06 UTC
Thank you for reaching out and helping us improve Vaex!

Before you submit a new Issue, please read through the [documentation](https://docs.vaex.io/en/latest/). Also, make sure you search through the Open and Closed Issues - your problem may already be discussed or addressed.

**Description**
Could you please explain how would be get the co-efficients of the variables/features used in sklearn regression models? The sklearn has a function called model.coef_ which gives us the coefficients of the variables used in the linear models. Is there something similar in vaex? I could not find any information about it in the documentation. I used dir(model) to look for any explanation.

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`: 3.0.0
 - Vaex was installed via: conda-forge
 - OS: bigSur

**Additional information**
Could you please explain how would be get the co-efficients of the variables/features used in sklearn regression models? The sklearn has a function called model.coef_ which gives us the coefficients of the variables used in the linear models. Is there something similar in vaex? I could not find any information about it in the documentation. I used dir(model) to look for any explanation.

**Comment by JovanVeljanoski** [comment] 2021-11-19 12:39
Duplicate of https://github.com/vaexio/vaex/issues/1722

**Closed by JovanVeljanoski** 2021-11-19 12:39 UTC
