### ISSUE TITLE
'open_many()' returns DataFrame with slicing issues

### ISSUE THREAD

**Issue by 1313e** [vaexio/vaex#578] opened 2020-02-05 04:29 UTC
I used the following code in order to create 3 different DataFrames, save all to HDF5 and then try to load them into a single DataFrame with `open_many`:
```python
import numpy as np
import vaex

# Generate list of random arrays
data_list = [np.random.rand(200, 4) for _ in range(3)]

# Create DataFrames for each array and export to HDF5
for i, data_arr in enumerate(data_list):
    # Create dict of data columns
    data_cols = {"x%i" % (j): col for j, col in enumerate(data_arr.T)}

    # Add index column to simulate multiple rows describing the same object
    index = np.arange(data_arr.shape[0])
    data_cols['index'] = index

    # Create DataFrame
    df = vaex.from_arrays(**data_cols)

    # Export to HDF5
    df.export_hdf5('data%i.hdf5' % (i))

# Load all three HDF5-files into a single DataFrame
df = vaex.open_many(['data%i.hdf5' % (i) for i in range(3)])

```

The DataFrame `df` that I have at the end does not work in the way I think is intended.
For example, trying to do show all rows that have `index == 50` with `df[df.index == 50]` gives "ValueError: array is of length 2, while the length of the DataFrame is 202" 3 times.
Similarly, showing all rows for `index < 3` with `df[df.index < 3]` gives a similar error, but `df[df.index < 4]` works perfectly fine.
Slicing also will not work properly, with `df[:10]` giving "ValueError: array is of length 11, while the length of the DataFrame is 10".

Most operations that require some form of slicing will not work properly.
However, they do work properly if I first sort the DataFrame on the `index` column.
For example, `df.sort('index')[:10]` returns the first 10 rows of the sorted DataFrame, whereas `df.sort('index')[df.index == 50]` returns what I would have expected earlier.

If I export this DataFrame to a single HDF5-file, load it with `vaex.open()`, then all of these errors go away and everything works as I would expect.
So, from this, I get the feeling that the `open_many()` function does not return a DataFrame properly or something.

Any ideas?

PS: Why does `vaex.__version__` return `'1.0.0-beta.6'`, even though the installed version is v2.6.1?

**Comment by maartenbreddels** [comment] 2020-02-07 20:04
Dear Ellert,

thanks for your report. I'm not sure what the problem is, but we don't test the concatenated dataframe a lot. I'll make sure all test also run on that, and see if I can reproduce these problems.
Indeed, exporting to a single file always works, and that is usually what we recommend.

The version issue is an artifact from when vaex was still 1 package, we should fix that!

Regards,

Maarten

**Comment by 1313e** [comment] 2020-02-08 01:31
Yeah, a single file is preferred.
I was however writing a database-system where more data can be added later, which would be stored in its own HDF5-file.
That would avoid me having to rewrite the entire HDF5-file every time I want to add something.
With concatenated DataFrames, this would be possible at a small speed penalty.

**Comment by JovanVeljanoski** [comment] 2021-07-09 12:25
This is now fixed. Thank you for reporting!
(single files are still preferred due to some performance reasons, but one should be able to work with concatenated dataframes without any issues).

**Closed by JovanVeljanoski** 2021-07-09 12:25 UTC
Labels: bug
