### ISSUE TITLE
[BUG-REPORT] Error when assign an column to an String 

### ISSUE THREAD

**Issue by ttpro1995** [vaexio/vaex#1020] opened 2020-10-22 04:00 UTC
**Description**
Please provide a clear and concise description of the problem. This should contain all the steps needed to reproduce the problem. A minimal code example that exposes the problem is very appreciated.

**Software information**
 - Vaex version 
```
{'vaex': '3.0.0',
 'vaex-core': '2.0.3',
 'vaex-viz': '0.4.0',
 'vaex-hdf5': '0.6.0',
 'vaex-server': '0.3.1',
 'vaex-astro': '0.7.0',
 'vaex-jupyter': '0.5.2',
 'vaex-ml': '0.9.0',
 'vaex-arrow': '0.5.1'}
```
 - Vaex was installed via: **pip** 
 - OS: Ubuntu 18.04 LTS

**Additional information**
Please state any supplementary information or provide additional context for the problem (e.g. screenshots, data, etc..).

**for-filter.txt**

```
a,b,c,d
1,2,3,4
2,6,7,8
-1,2,3,4
4,5,5,5
-2,3,3,3
```

Code run on Jupyterlab
```
import pandas as pd
import vaex as vx
import numpy as np
df_vaex = vx.read_csv("for-filter.txt")
df_vaex["e"] = "five"
df_vaex
```

Error output

```
ERROR:MainThread:vaex:error evaluating: e at rows 0-5
Traceback (most recent call last):
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 97, in evaluate
    result = self[expression]
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 144, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: 'five'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 1996, in data_type
    data = self.evaluate(expression, 0, 1, filtered=False, internal=True, parallel=False)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 2616, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 5427, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 97, in evaluate
    result = self[expression]
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 139, in __getitem__
    self.values[variable] = self.evaluate(expression)  # , out=self.buffers[variable])
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 103, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
NameError: name 'five' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 97, in evaluate
    result = self[expression]
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 144, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: 'five'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 3575, in table_part
    values = dict(zip(column_names, df.evaluate(column_names)))
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 2616, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 5352, in _evaluate_implementation
    dtypes[expression] = df.data_type(expression, internal=False)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 1998, in data_type
    data = self.evaluate(expression, 0, 1, filtered=True, internal=True, parallel=False)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 2616, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 5427, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 97, in evaluate
    result = self[expression]
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 139, in __getitem__
    self.values[variable] = self.evaluate(expression)  # , out=self.buffers[variable])
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 103, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
NameError: name 'five' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 97, in evaluate
    result = self[expression]
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 144, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: 'five'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 1996, in data_type
    data = self.evaluate(expression, 0, 1, filtered=False, internal=True, parallel=False)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 2616, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 5427, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 97, in evaluate
    result = self[expression]
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 139, in __getitem__
    self.values[variable] = self.evaluate(expression)  # , out=self.buffers[variable])
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 103, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
NameError: name 'five' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 97, in evaluate
    result = self[expression]
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 144, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: 'five'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 3580, in table_part
    values[name] = df.evaluate(name)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 2616, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 5352, in _evaluate_implementation
    dtypes[expression] = df.data_type(expression, internal=False)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 1998, in data_type
    data = self.evaluate(expression, 0, 1, filtered=True, internal=True, parallel=False)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 2616, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 5427, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 97, in evaluate
    result = self[expression]
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 139, in __getitem__
    self.values[variable] = self.evaluate(expression)  # , out=self.buffers[variable])
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 103, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
NameError: name 'five' is not defined
ERROR:MainThread:vaex:error evaluating: e at rows 0-5
Traceback (most recent call last):
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 97, in evaluate
    result = self[expression]
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 144, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: 'five'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 1996, in data_type
    data = self.evaluate(expression, 0, 1, filtered=False, internal=True, parallel=False)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 2616, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 5427, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 97, in evaluate
    result = self[expression]
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 139, in __getitem__
    self.values[variable] = self.evaluate(expression)  # , out=self.buffers[variable])
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 103, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
NameError: name 'five' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 97, in evaluate
    result = self[expression]
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 144, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: 'five'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 3575, in table_part
    values = dict(zip(column_names, df.evaluate(column_names)))
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 2616, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 5352, in _evaluate_implementation
    dtypes[expression] = df.data_type(expression, internal=False)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 1998, in data_type
    data = self.evaluate(expression, 0, 1, filtered=True, internal=True, parallel=False)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 2616, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 5427, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 97, in evaluate
    result = self[expression]
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 139, in __getitem__
    self.values[variable] = self.evaluate(expression)  # , out=self.buffers[variable])
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 103, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
NameError: name 'five' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 97, in evaluate
    result = self[expression]
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 144, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: 'five'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 1996, in data_type
    data = self.evaluate(expression, 0, 1, filtered=False, internal=True, parallel=False)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 2616, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 5427, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 97, in evaluate
    result = self[expression]
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 139, in __getitem__
    self.values[variable] = self.evaluate(expression)  # , out=self.buffers[variable])
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 103, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
NameError: name 'five' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 97, in evaluate
    result = self[expression]
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 144, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: 'five'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 3580, in table_part
    values[name] = df.evaluate(name)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 2616, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 5352, in _evaluate_implementation
    dtypes[expression] = df.data_type(expression, internal=False)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 1998, in data_type
    data = self.evaluate(expression, 0, 1, filtered=True, internal=True, parallel=False)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 2616, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/dataframe.py", line 5427, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 97, in evaluate
    result = self[expression]
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 139, in __getitem__
    self.values[variable] = self.evaluate(expression)  # , out=self.buffers[variable])
  File "/home/cpu11453/miniconda3/envs/vaex/lib/python3.8/site-packages/vaex/scopes.py", line 103, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
NameError: name 'five' is not defined
```

Expected: 

It should add new column name "e" with value "five" like Pandas would do. Or output more meaningful error insight.

**Comment by JovanVeljanoski** [comment] 2020-10-22 17:11
Duplicate of #1019

**Closed by JovanVeljanoski** 2020-10-22 17:11 UTC
