### ISSUE TITLE
Vaex fails opening partitioned Parquet file

### ISSUE THREAD

**Issue by theophilechevalier** [vaexio/vaex#834] opened 2020-06-15 16:30 UTC
I have a local parquet files splitted in 28 partitions (~370M rows, 4.1Gb in snappy):
```
activities.parquet/
|___ activities-e502fb49-a1e7-49bd-8dbf-75468732cb45.snappy.parquet
|___ activities-d522fcf6-19f6-4855-8541-032bd5c0fbd5.snappy.parquet
|___ ...
```

I'm able to open it but `df.head()` with `vaex` raises:
```
ValueError: array is of length 13514680, while the length of the DataFrame is 370889861
```
I don't have any problem reading it with `arrow` or `pandas`.

I haven't investigated that much to be honest!

Vaex versions:
```
In [9]: vaex.__version__
Out[9]:
{'vaex': '3.0.0',
 'vaex-core': '2.0.3',
 'vaex-viz': '0.4.0',
 'vaex-hdf5': '0.6.0',
 'vaex-server': '0.3.1',
 'vaex-astro': '0.7.0',
 'vaex-jupyter': '0.5.2',
 'vaex-ml': '0.9.0',
 'vaex-arrow': '0.5.1'}
```
Tested under Python38 & Python37

Complete traceback:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-c42a15b2c7cf> in <module>
----> 1 df.head()

/usr/local/lib/python3.8/site-packages/vaex/dataframe.py in head(self, n)
   3449     def head(self, n=10):
   3450         """Return a shallow copy a DataFrame with the first n rows."""
-> 3451         return self[:min(n, len(self))]
   3452
   3453     def tail(self, n=10):

/usr/local/lib/python3.8/site-packages/vaex/dataframe.py in __getitem__(self, item)
   4624                 assert stop != -1
   4625                 stop = stop+1  # +1 to make it inclusive
-> 4626             df = self.trim()
   4627             df.set_active_range(start, stop)
   4628             return df.trim()

/usr/local/lib/python3.8/site-packages/vaex/dataframe.py in trim(self, inplace)
   3857         :rtype: DataFrame
   3858         '''
-> 3859         df = self if inplace else self.copy()
   3860         if self._index_start == 0 and self._index_end == self._length_original:
   3861             return df

/usr/local/lib/python3.8/site-packages/vaex/dataframe.py in copy(self, column_names, virtual)
   5034                 if name in self.columns:
   5035                     column = self.columns[name]
-> 5036                     df.add_column(name, column, dtype=self._dtypes_override.get(name))
   5037                     if isinstance(column, ColumnSparse):
   5038                         df._sparse_matrices[name] = self._sparse_matrices[name]

/usr/local/lib/python3.8/site-packages/vaex/dataframe.py in add_column(self, name, data, dtype)
   6051         #     self._length_original = len(data)
   6052         #     self._index_end = self._length_unfiltered
-> 6053         super(DataFrameArrays, self).add_column(name, data, dtype=dtype)
   6054         self._length_unfiltered = int(round(self._length_original * self._active_fraction))
   6055         # self.set_active_fraction(self._active_fraction)

/usr/local/lib/python3.8/site-packages/vaex/dataframe.py in add_column(self, name, f_or_array, dtype)
   2940                     if len(self) == len(ar):
   2941                         raise ValueError("Array is of length %s, while the length of the DataFrame is %s due to the filtering, the (unfiltered) length is %s." % (len(ar), len(self), self.length_unfiltered()))
-> 2942                 raise ValueError("array is of length %s, while the length of the DataFrame is %s" % (len(ar), self.length_original()))
   2943             # assert self.length_unfiltered() == len(data), "columns should be of equal length, length should be %d, while it is %d" % ( self.length_unfiltered(), len(data))
   2944             valid_name = vaex.utils.find_valid_name(name, used=self.get_column_names(hidden=True))

ValueError: array is of length 13514680, while the length of the DataFrame is 370889861
```

**Comment by theophilechevalier** [comment] 2020-06-15 16:54
Minimal example to reproduce:
```python
import vaex
import pandas as pd
import numpy as np

df = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
).to_parquet("test.parquet", engine='pyarrow', compression='snappy', partition_cols=["E"])

df = vaex.open("test.parquet")
df.head()
```

**Comment by maartenbreddels** [comment] 2020-06-16 07:13
Hi Theophile,

Thanks for the reproducible example. In master, we don't support Arrow chunks yet, so I think that is the main issue. In #517 we do, but it's triggering a different issue. Please keep an eye on that branch, once we have that merged and release this should work well.

cheers,

Maarten

**Comment by alrz199** [comment] 2020-06-18 07:01
@theophilechevalier 
check that df.tail is working or not. maybe vaex reads  the file and df.head is not working

**Comment by EmilGuliyev** [comment] 2020-08-28 11:40
Hi Maarten,

Is there any update on this bug? 

I have gzipped json files and I can't directly load them all without conversion. when I convert them to hdf5, size becomes too big, but .parquet export only saves it with the same size of zipped json so I convert everything to ".parquet" format. When I load all converted .parquet files in  vaex.open or vaex.open_many, I get same error:

"ValueError: array is of length xxxx, while the length of the DataFrame is  xxxxx"

Thank you,

Emil

**Comment by remilapeyre** [comment] 2020-09-07 20:07
It seems like this is fixed on master now.

**Comment by aburkov** [comment] 2020-11-21 00:03
I have a similar problem but a different error message:

```
ERROR:MainThread:vaex.file:could not read 4 bytes from 's3://product-dev/input/parquet/dump-20201010'
Traceback (most recent call last):
  File "/home/someuser/anaconda3/lib/python3.8/site-packages/s3fs/core.py", line 525, in info
    out = self._call_s3(self.s3.head_object, kwargs, Bucket=bucket,
  File "/home/someuser/anaconda3/lib/python3.8/site-packages/s3fs/core.py", line 195, in _call_s3
    return method(**additional_kwargs)
  File "/home/someuser/anaconda3/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/someuser/anaconda3/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/someuser/anaconda3/lib/python3.8/site-packages/vaex/hdf5/dataset.py", line 152, in can_open
    with s3.open(path, "rb") as f:
  File "/home/someuser/anaconda3/lib/python3.8/site-packages/vaex/file/s3.py", line 47, in open
    fp = vaex.file.cache.CachedFile(fp, naked_path)
  File "/home/someuser/anaconda3/lib/python3.8/site-packages/vaex/file/cache.py", line 90, in __init__
    self._use_file()
  File "/home/someuser/anaconda3/lib/python3.8/site-packages/vaex/file/cache.py", line 125, in _use_file
    self.file = self.file()
  File "/home/someuser/anaconda3/lib/python3.8/site-packages/vaex/file/s3.py", line 46, in <lambda>
    fp = lambda: s3.open(naked_path, mode)
  File "/home/someuser/anaconda3/lib/python3.8/site-packages/s3fs/core.py", line 350, in open
    fdesc = S3File(self, path, mode2, block_size=block_size, acl=acl,
  File "/home/someuser/anaconda3/lib/python3.8/site-packages/s3fs/core.py", line 1210, in __init__
    info = self.info()
  File "/home/someuser/anaconda3/lib/python3.8/site-packages/s3fs/core.py", line 1227, in info
    return self.s3.info(self.path, version_id=self.version_id,
  File "/home/someuser/anaconda3/lib/python3.8/site-packages/s3fs/core.py", line 537, in info
    raise_from(FileNotFoundError(path), e)
  File "<string>", line 3, in raise_from
FileNotFoundError: product-dev/input/parquet/dump-20201010
ERROR:MainThread:vaex:error opening 's3://product-dev/input/parquet/dump-20201010'
Traceback (most recent call last):
  File "/home/someuser/p/VS_Code_Projects/SkillExtractor/vaex_test.py", line 5, in <module>
    df = vaex.open(original_data_source)
  File "/home/someuser/anaconda3/lib/python3.8/site-packages/vaex/__init__.py", line 226, in open
    raise IOError('Unknown error opening: {}'.format(path))
OSError: Unknown error opening: s3://product-dev/input/parquet/dump-20201010
```

**Comment by maartenbreddels** [comment] 2020-11-21 07:05
Hi Andriy,

vaex has no buildin support for partitioned datasets yet. We can support that via arrow, but we didn't implement this yet. Using the latest alphas you should be able to do the following:
```
$ pip install vaex-core==4.0.0a5
```

```python
import vaex
df = vaex.open('s3://product-dev/input/parquet/dump-20201010/**/*.parquet')
```

Another path, would be to use arrow directly (see https://arrow.apache.org/docs/python/dataset.html#reading-from-cloud-storage):
```python
from pyarrow import fs

s3  = fs.S3FileSystem(region="us-east-2")
dataset = ds.dataset("product-dev/", filesystem=s3,
                     partitioning=["country_code"])

import vaex
df = vaex.from_arrow_dataset(dataset)
```

Hope that helps.

cheers,

Maarten

**Comment by maartenbreddels** [comment] 2020-11-21 08:00
PS: We don't come from a spark background, so it things are a bit odd for you, let us know how we can improve migration pains.

**Comment by aburkov** [comment] 2020-11-21 08:14
I'm reeeally impressed by vaex, seriously. After Spark, a breath of fresh air. Just ran it on a tiny machine and the speed was incredible! So I'm definitely willing to wait for the partitioned parquet support. I tried your advice to install vaex-core==4.0.0a5 but I have the following error during installation:

```
vaex 3.0.0 requires vaex-core<3,>=2.0.0, but you'll have vaex-core 4.0.0a5 which is incompatible.
vaex-viz 0.4.0 requires vaex-core<3,>=2.0.0, but you'll have vaex-core 4.0.0a5 which is incompatible.
vaex-server 0.3.1 requires vaex-core<3,>=2.0.0, but you'll have vaex-core 4.0.0a5 which is incompatible.
vaex-ml 0.9.0 requires vaex-core<3,>=2.0.0, but you'll have vaex-core 4.0.0a5 which is incompatible.
vaex-jupyter 0.5.2 requires vaex-core<3,>=2.0.0, but you'll have vaex-core 4.0.0a5 which is incompatible.
vaex-hdf5 0.6.0 requires vaex-core<3,>=2.0.0, but you'll have vaex-core 4.0.0a5 which is incompatible.
vaex-astro 0.7.0 requires vaex-core<3,>=2.0.0-alpha.1, but you'll have vaex-core 4.0.0a5 which is incompatible.
vaex-arrow 0.5.1 requires vaex-core<3,>=2.0.0, but you'll have vaex-core 4.0.0a5 which is incompatible.
Successfully installed blake3-0.1.8 frozendict-1.2 vaex-core-4.0.0a5
```

After that, "import vaex" doesn't work:

```
>>> import vaex
ERROR:MainThread:vaex:issue loading plot
Traceback (most recent call last):
  File "/home/someuser/anaconda3/lib/python3.8/site-packages/vaex/__init__.py", line 768, in <module>
    add_namespace = entry.load()
  File "/home/someuser/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/home/someuser/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/someuser/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (vaex-core 4.0.0a5 (/home/someuser/anaconda3/lib/python3.8/site-packages), Requirement.parse('vaex-core<3,>=2.0.0'))
ERROR:MainThread:vaex:issue loading astro
Traceback (most recent call last):
  File "/home/someuser/anaconda3/lib/python3.8/site-packages/vaex/__init__.py", line 768, in <module>
    add_namespace = entry.load()
  File "/home/someuser/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/home/someuser/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/someuser/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (vaex-core 4.0.0a5 (/home/someuser/anaconda3/lib/python3.8/site-packages), Requirement.parse('vaex-core<3,>=2.0.0-alpha.1'))
```

Do you have an idea of how to make it work?

**Comment by maartenbreddels** [comment] 2020-11-21 08:56
Thanks for your enthousiasm, very encouraging :)

I think these are only 'warnings', and vaex should work fine, however it can be fixed.

Vaex consist of a set of packages, the `vaex` package installs all of them for convenience. But for the alpha version we didn't release it yet, so you have old `vaex-astro` and `vaex-viz` installed, which conflicts with the latest vaex-core.

```
$ pip list | grep vaex
# to uninstall them all
$ pip list | grep vaex | awk '{print $1}' | xargs pip uninstall -y
```

You only need `vaex-core` for your purpose.

Btw, do you really need the support for partitioning? Or would using all parquet files (concatenting them as 1 dataframe using the trick shared above be good enough).

**Comment by aburkov** [comment] 2020-11-21 21:46
Thank you! I think that for people who previously used Spark, it would be convenient to be able to provide a partitioned parquet as an argument for vaex.open() but you are right, one can simply create a list of partitions and provide this list as an argument to open_many. It's just less convenient.

**Comment by Jbollenbacher** [comment] 2020-12-02 07:13
Dask also partitions parquets by default, so support for partitioned parquets would be helpful to Dask users as well.

**Comment by maartenbreddels** [comment] 2020-12-02 15:36
I agree.

I've implemented Hive partitioning support in https://github.com/vaexio/vaex/pull/1094 I'd appreciate some feedback on that, for instance, I might miss something trivial.

**Closed** 2020-12-07 11:36 UTC
Labels: bug

**Comment by velvia** [comment] 2020-12-08 01:03
I can confirm that 4.0.0-a5 fixes the partitioned Parquet read issue, and that I also wish .open() on a Parquet dir would just work.

**Comment by maartenbreddels** [comment] 2020-12-08 18:22
This now work due to #1094, to install:
```
$ pip install "vaex-core>=4.0.0a11"
# or for the while kitchsink:
$ pip install "vaex>=4.0.0a6"
```
