### ISSUE TITLE
[BUG-REPORT] - ArrowInvalid: offset overflow while concatenating arrays

### ISSUE THREAD

**Issue by Ben-Epstein** [vaexio/vaex#1650] opened 2021-10-15 20:38 UTC
Thank you for reaching out and helping us improve Vaex!

Before you submit a new Issue, please read through the [documentation](https://docs.vaex.io/en/latest/). Also, make sure you search through the Open and Closed Issues - your problem may already be discussed or addressed.

**Description**
When doing operations on large dataframes with long string columns (~500 characters), slicing the dataframe results in the error 
```
ArrowInvalid: offset overflow while concatenating arrays
```

This doesn't happen with small datasets, and also doesn't happen with short strings. It's explicitly a problem with many large strings.

Example
```
import vaex
from vaex.dataframe import DataFrame
from random import random
import numpy as np
x = str(random())*25
def create_test_df(
    num_samples: int = 10000000, num_classes: int = 20
):

    id_column = np.arange(num_samples)
    val1 = np.random.randint(0, 20, size=num_samples)
    val2 = np.random.randint(0, 20, size=num_samples)
    text_data = [x for _ in range(num_samples)]

    score = np.random.uniform(0, 1.0, size=num_samples)

    matrix = {
        'id': id_column,
        'val1': val1,
        'val2': val2,
        'score': score,
        'text': text_data
    }
    return vaex.from_arrays(**matrix)

d2 = create_test_df(num_samples=10000000)
d2.sort(by='score')[0:500].to_records()
```

In the trace, I see this 
```
~/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/vaex/column.py in __getitem__(self, slice)
    283             take_indices[mask] = 0
    284         if isinstance(ar_unfiltered, supported_arrow_array_types):
--> 285             ar = ar_unfiltered.take(vaex.array_types.to_arrow(take_indices))
    286         else:
    287             ar = ar_unfiltered[take_indices]
```

which lead me to some investigation and found [this](https://github.com/huggingface/datasets/issues/615) and [this](https://github.com/huggingface/datasets/pull/645/files) - I think you need to switch to using `.slice` instead of `.take` 

Do you have any ideas for a workaround I can use for now?

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`:
```
{'vaex': '4.5.0',
 'vaex-core': '4.5.1',
 'vaex-viz': '0.5.0',
 'vaex-hdf5': '0.10.0',
 'vaex-server': '0.6.1',
 'vaex-astro': '0.9.0',
 'vaex-jupyter': '0.6.0',
 'vaex-ml': '0.14.0'}
```
 - Vaex was installed via: pip / conda-forge / from source - pip
 - OS: Macos big sur

**Additional information**
Please state any supplementary information or provide additional context for the problem (e.g. screenshots, data, etc..).

**Comment by Ben-Epstein** [comment] 2021-10-17 18:15
I found a workaround for me in case anyone runs into a similar situation. Maybe it'll help with debugging?

```import vaex
from vaex.dataframe import DataFrame
from random import random
import numpy as np


x = str(random())*25
def create_test_df(
    num_samples: int = 10000000, num_classes: int = 20
):

    id_column = np.arange(num_samples)
    val1 = np.random.randint(0, 20, size=num_samples)
    val2 = np.random.randint(0, 20, size=num_samples)
    text_data = [x for _ in range(num_samples)]

    score = np.random.uniform(0, 1.0, size=num_samples)

    matrix = {
        'id': id_column,
        'val1': val1,
        'val2': val2,
        'score': score,
        'text': text_data
    }
    return vaex.from_arrays(**matrix)


d2 = create_test_df(num_samples=10000000)


# Separate out score
df_score = d2[["score", "id"]]
# Sort by score and get the sorted IDs to use later
sorted_df = df_score.sort(by='score')[:500]
sorted_ids = sorted_df[["id"]].to_arrays(array_type="list")[0]

data_samples = d2[d2["id"].isin(sorted_ids)].to_records()
# sort the data_samples by the sorted_ids
data_samples = {row["id"]: row for row in data_samples}
data_samples = [row[id] for id in sorted_ids]
```

Obviously this isn't ideal but it's the best performance I could get.

**Comment by JovanVeljanoski** [comment] 2021-11-13 23:13
This problem arises from using `df.take` with strings that are longer than a certain length. Either something with arrow, or how vaex uses arrow, but it is a long bug. I think it crashes only for long strings. 

In your original case, if you set `x = str(random())*1` the example will work.

**Comment by JovanVeljanoski** [comment] 2021-11-13 23:18
Closing as duplicate of 
https://github.com/vaexio/vaex/issues/1097

**Closed by JovanVeljanoski** 2021-11-13 23:18 UTC
Labels: bug

**Comment by hermidalc** [comment] 2022-10-12 19:48
Is there a workaround for this bug? I'm running into this problem. I don't believe I have strings that are long, but for some reason I also cannot find the max length of a str column by doing `df.col_name.str.len()` it throws a `NotImplementedError`

**Comment by JovanVeljanoski** [comment] 2022-10-12 19:51
Which pyarrow version do you use? Upgrading might help. 
Otherwise please submit a reproducible example -  i can't reproduce your problem

**Comment by hermidalc** [comment] 2022-10-12 19:58
pyarrow 9.0.0 from conda-forge. It will take me a bit to create a reprex have to figure out what the max string length actually is in my very large dataframe (300 million rows x 3 str columns).

**Comment by JovanVeljanoski** [comment] 2022-10-12 20:01
I just tried on a 600M dataframe, and it works just fine.. so. i am afraid some kind of preproducible example that we can run locally is a must..

**Comment by hermidalc** [comment] 2022-10-12 20:20
> I just tried on a 600M dataframe, and it works just fine.. so. i am afraid some kind of preproducible example that we can run locally is a must..
> 
> Also maybe best to open a new issue if you can reproduce it so we can track it better

It appears to be after I joined two dataframes, because each separate dataframe was already and HDF5 file originally exported from vaex, and when I load each separately and write back to and HDF5 all is ok. But when I inner join both dataframe on the common column, the when trying to export this to HDF5 I get the overflow error mentioned in this thread. I will try to create a reprex just first trying to troubleshoot the source of the problem because not possible to make a reprex without first sort of knowing what triggers the issue. My data is too large to make into a reprex for you.

**Comment by hermidalc** [comment] 2022-10-12 20:24
And @JovanVeljanoski don't you find this strange? Because what I just described doing above proves that it's not a str length problem, because I added no new data, I just joined a 2 string column dataframe with a 3 string column dataframe on the common column (with `allow_duplication=True` as the common column doesn't have unique values), and each independent dataframe has no problems loading from or exporting to HDF5.

**Comment by hermidalc** [comment] 2022-10-13 13:45
@JovanVeljanoski I sent you an email with a reproducible example using my real data (too big to attach here)

**Comment by bestpredicts** [comment] 2023-02-28 22:53
same error here
