### ISSUE TITLE
issue on vaex install with pip

### ISSUE THREAD

**Issue by GaranceRichard** [vaexio/vaex#686] opened 2020-04-21 12:26 UTC
i did on windows 10 : pip install vaex
tried to use it in jupyter

ImportError                               Traceback (most recent call last)
<ipython-input-1-13d82a525057> in <module>
      4 import matplotlib.pyplot as plt
      5 import pickle
----> 6 import vaex as pd
      7 import glob
      8 from scipy import ndarray

c:\users\ia\appdata\local\programs\python\python37\lib\site-packages\vaex\__init__.py in <module>
     37 import six
     38 
---> 39 import vaex.dataframe
     40 import vaex.dataset
     41 from vaex.functions import register_function

c:\users\ia\appdata\local\programs\python\python37\lib\site-packages\vaex\dataframe.py in <module>
     15 import threading
     16 import six
---> 17 import vaex.utils
     18 # import vaex.image
     19 import numpy as np

c:\users\ia\appdata\local\programs\python\python37\lib\site-packages\vaex\utils.py in <module>
     22 import yaml
     23 
---> 24 from .column import str_type
     25 from .json import VaexJsonEncoder, VaexJsonDecoder
     26 

c:\users\ia\appdata\local\programs\python\python37\lib\site-packages\vaex\column.py in <module>
      7 on_rtd = os.environ.get('READTHEDOCS', None) == 'True'
      8 if not on_rtd:
----> 9     import vaex.strings
     10 
     11 logger = logging.getLogger("vaex.column")

c:\users\ia\appdata\local\programs\python\python37\lib\site-packages\vaex\strings.py in <module>
      5 on_rtd = os.environ.get('READTHEDOCS', None) == 'True'
      6 if not on_rtd:
----> 7     from .superstrings import *
      8 
      9 def array(ar):

ImportError: DLL load failed: Le module spécifié est introuvable.ImportError                               Traceback (most recent call last)
<ipython-input-1-13d82a525057> in <module>
      4 import matplotlib.pyplot as plt
      5 import pickle
----> 6 import vaex as pd
      7 import glob
      8 from scipy import ndarray

c:\users\ia\appdata\local\programs\python\python37\lib\site-packages\vaex\__init__.py in <module>
     37 import six
     38 
---> 39 import vaex.dataframe
     40 import vaex.dataset
     41 from vaex.functions import register_function

c:\users\ia\appdata\local\programs\python\python37\lib\site-packages\vaex\dataframe.py in <module>
     15 import threading
     16 import six
---> 17 import vaex.utils
     18 # import vaex.image
     19 import numpy as np

c:\users\ia\appdata\local\programs\python\python37\lib\site-packages\vaex\utils.py in <module>
     22 import yaml
     23 
---> 24 from .column import str_type
     25 from .json import VaexJsonEncoder, VaexJsonDecoder
     26 

c:\users\ia\appdata\local\programs\python\python37\lib\site-packages\vaex\column.py in <module>
      7 on_rtd = os.environ.get('READTHEDOCS', None) == 'True'
      8 if not on_rtd:
----> 9     import vaex.strings
     10 
     11 logger = logging.getLogger("vaex.column")

c:\users\ia\appdata\local\programs\python\python37\lib\site-packages\vaex\strings.py in <module>
      5 on_rtd = os.environ.get('READTHEDOCS', None) == 'True'
      6 if not on_rtd:
----> 7     from .superstrings import *
      8 
      9 def array(ar):

ImportError: DLL load failed: Le module spécifié est introuvable.

**Comment by maartenbreddels** [comment] 2020-04-22 19:53
Dear Garance,

I think this is a duplicate of https://github.com/vaexio/vaex/issues/630, please let me know if that solved it. If not, feel tree to re-open. A future release will contain this fix for sure!

Regards,

Maarten

**Closed by maartenbreddels** 2020-04-22 19:53 UTC
