### ISSUE TITLE
ml: Support TensorFlow via Apache Arrow / tensorflow_io

### ISSUE THREAD

**Issue by maartenbreddels** [vaexio/vaex#520] opened 2019-12-21 17:48 UTC
With https://github.com/tensorflow/io we should be able to get a Tensorflow DataSet with the dataset flowing over Arrow record batches. This depends on Apache Arrow PR #517 and a record batch iterator based on #516

**Comment by JovanVeljanoski** [comment] 2020-04-29 12:44
I will close this since duplicate of #616

**Closed by JovanVeljanoski** 2020-04-29 12:44 UTC
Labels: feature-request
