### ISSUE TITLE
[FEATURE-REQUEST] Best compatible tools for MLOPS?

### ISSUE THREAD

**Issue by enthusiastics** [vaexio/vaex#1555] opened 2021-08-30 00:53 UTC
Hi,

I just found Vaex and I think this is an extremely valuable technology, especially for my use case where we require very fast and scalable computation. I actually want to put Vaex into production. But I would like to ask what is the most compatible streaming data tools and database to use (basically, I would need to stream data, apply realtime transformation, output real time prediction, and also store results into database for future reference (or future restarts.))? I really want to apply Vaex to tick data where there is massive volume and per second and high speed analysis is needed.

**Comment by JovanVeljanoski** [comment] 2021-08-30 07:45
Closing as duplicate of #1554. This is not a bug-report or a feature request, but a question so it belongs in the discussions where it was first opened.

**Closed by JovanVeljanoski** 2021-08-30 07:45 UTC
