### ISSUE TITLE
Assign functionality

### ISSUE THREAD

**Issue by argenisleon** [vaexio/vaex#1329] opened 2021-04-27 16:33 UTC
Hi Guys,

Is there any assign function like in pandas in Vaex?
I would like to return a modified dataframe without modifying the original one?
Below some pandas code
```
import pandas as pd
df = pd.DataFrame({'temp_c': [17.0, 25.0]},
                  index=['Portland', 'Berkeley'])

	temp_c
Portland	17.0
Berkeley	25.0
```
```
df.assign(temp_f=lambda x: x.temp_c * 9 / 5 + 32)

	temp_c	temp_f
Portland	17.0	62.6
Berkeley	25.0	77.0
```

**Comment by JovanVeljanoski** [comment] 2021-04-27 19:16
Hi, 

Maybe you can take a look at #972, seems to be a duplicate of this. 

Btw, with vaex when you create new expressions the original data is never modified. 

I will close this, so please continue the discussion in the other thread ( to keep things more focused and easier to find). 

Thanks!

**Closed by JovanVeljanoski** 2021-04-27 19:16 UTC
