### ISSUE TITLE
Trying to filter a column exactly as I did to another, but It's returning an error

### ISSUE THREAD

**Issue by kaburelabs** [vaexio/vaex#974] opened 2020-09-19 20:15 UTC
Hello guys,

I have tried to filter my table by country... But it's not working.

I tried a lot of different approaches and workarounds about it still not working, I think that it is a bug;

When I try it on the segment column it works: 
![image](https://user-images.githubusercontent.com/24701735/93688244-beba2800-fa9a-11ea-988d-99fbcbd10c0e.png)

When trying to filter other features/columns, it only works when using the "head" (I discovered it right now to write this issue lol) 

![image](https://user-images.githubusercontent.com/24701735/93688267-ffb23c80-fa9a-11ea-9680-7e16ab1e8915.png)

But when trying to filter without the .head() method it returns an error to me:

![image](https://user-images.githubusercontent.com/24701735/93688345-8830dd00-fa9b-11ea-92dc-0dbfcfa75540.png)

Could someone explain what I'm doing wrong or confirm if it is a bug? 

Thank you very much in advance;

Best Regards,
Leonardo

**Comment by JovanVeljanoski** [comment] 2020-09-20 09:33
Hi, 

I am not reproduce this issue.
Can you please provide a reproducible example, and also answer the questions that are asked in the Issue template.

**Comment by kaburelabs** [comment] 2020-09-21 00:39
Hey Jovan, thanks for answering me;

I can't reproduce it because I'm not understanding what is happening. I have a table with 166k rows and if I sample it by 150k it works, but when filtering the whole dataset it doesn't work. EXCLUSIVELY IN THIS COLUMN! 

But ok, I did some workarounds and I made it run... Thanks

**Comment by JovanVeljanoski** [comment] 2020-09-21 05:49
Can you investigate the contents of the column? Is it of dtype object perhaps? It might show up as string, depending on how you are loading the data (did you convert your data to hdf5 or arrow?). See for the presence of np.nan or None, or masked values. See where they appear in relation to your filter. Something like that.

**Comment by maartenbreddels** [comment] 2020-09-21 07:20
Hi Leonardo,

thanks for the issue, but as Jovan said, we need some more details. This generally works, so there must be something special triggering this bug.
You could also try https://pypi.org/project/vaex-core/4.0.0a2/

Regards,

Maarten

**Comment by maartenbreddels** [comment] 2020-09-24 17:51
Hmm, actually, I think this is a duplicate of https://github.com/vaexio/vaex/issues/928

**Comment by maartenbreddels** [comment] 2020-09-24 17:51
I'll close this and so we can track that.

**Closed by maartenbreddels** 2020-09-24 17:51 UTC
