### ISSUE TITLE
aggregation operations inside the groupby-method for column with type string

### ISSUE THREAD

**Issue by salwaen** [vaexio/vaex#937] opened 2020-08-17 03:38 UTC
Hi,
###  in pandas I get min or max value from columns with type string

````
d = {'col1': [1, 1, 2, 2, 3], 'col2':['monday', 'mon', 'sunday', 'sun', 'Thursday']}
df = pd.DataFrame(data=d)
df = df.groupby(df['col1']).agg({'col2':'min'})

````
### the output

````
         col2
col1          
1          mon
2          sun
3     Thursday

````
### in vaex

````
x = [1, 1, 2, 2, 3]
y = ['monday', 'mon', 'sunday', 'sun', 'Thursday']
df = vaex.from_arrays(col1=x, col2=y)
df = df.groupby(df['col1']).agg({'col2':'min'})
````
### the outpuot

````
  File "D:/dash-120million-taxi-app/test.py", line 25, in <module>
    df = df.groupby(df['col1']).agg({'col2':'min'})
  File "D:\dash-120million-taxi-app\venv\lib\site-packages\vaex\groupby.py", line 255, in agg
    self.df.execute()
  File "D:\dash-120million-taxi-app\venv\lib\site-packages\vaex\dataframe.py", line 315, in execute
    just_run(self.execute_async())
  File "D:\dash-120million-taxi-app\venv\lib\site-packages\vaex\asyncio.py", line 35, in just_run
    return loop.run_until_complete(coro)
  File "D:\dash-120million-taxi-app\venv\lib\site-packages\nest_asyncio.py", line 95, in run_until_complete
    return f.result()
  File "C:\Users\salchehabi\AppData\Local\Programs\Python\Python36\lib\asyncio\tasks.py", line 180, in _step
    result = coro.send(None)
  File "D:\dash-120million-taxi-app\venv\lib\site-packages\vaex\dataframe.py", line 320, in execute_async
    await self.executor.execute_async()
  File "D:\dash-120million-taxi-app\venv\lib\site-packages\vaex\execution.py", line 145, in execute_async
    task._parts = [encoding.decode('task-part-cpu', spec, df=run.df) for i in range(self.thread_pool.nthreads)]
  File "D:\dash-120million-taxi-app\venv\lib\site-packages\vaex\execution.py", line 145, in <listcomp>
    task._parts = [encoding.decode('task-part-cpu', spec, df=run.df) for i in range(self.thread_pool.nthreads)]
  File "D:\dash-120million-taxi-app\venv\lib\site-packages\vaex\encoding.py", line 217, in decode
    decoded = self.registry[typename].decode(self, value, **kwargs)
  File "D:\dash-120million-taxi-app\venv\lib\site-packages\vaex\cpu.py", line 36, in decode
    return cls.decode(encoding, spec, df)
  File "D:\dash-120million-taxi-app\venv\lib\site-packages\vaex\cpu.py", line 411, in decode
    return cls(df, grid, aggs, dtypes)
  File "D:\dash-120million-taxi-app\venv\lib\site-packages\vaex\cpu.py", line 306, in __init__
    self.aggregations.append((aggregator_descriptor, selections, create_aggregator(aggregator_descriptor, selections), selection_waslist))
  File "D:\dash-120million-taxi-app\venv\lib\site-packages\vaex\cpu.py", line 299, in create_aggregator
    return [aggregator_descriptor._create_operation(self.df, self.grid) for selection in selections]
  File "D:\dash-120million-taxi-app\venv\lib\site-packages\vaex\cpu.py", line 299, in <listcomp>
    return [aggregator_descriptor._create_operation(self.df, self.grid) for selection in selections]
  File "D:\dash-120million-taxi-app\venv\lib\site-packages\vaex\agg.py", line 109, in _create_operation
    agg_op_type = vaex.utils.find_type_from_dtype(vaex.superagg, self.name + "_", self.dtype_in)
  File "D:\dash-120million-taxi-app\venv\lib\site-packages\vaex\utils.py", line 882, in find_type_from_dtype
    raise ValueError('Could not find a class (%s), seems %s is not supported' % (name, dtype))
ValueError: Could not find a class (AggMin_string), seems <class 'str'> is not supported
````

**Comment by maartenbreddels** [comment] 2020-09-21 10:17
Thanks for the issue, it's a duplicate of https://github.com/vaexio/vaex/issues/832, please subscribe to that for updates.

Regards,

Maarten

**Closed by maartenbreddels** 2020-09-21 10:17 UTC
